# frozen_string_literal: true
module Schedule

  IPL_SCHEDULE = [
      { match_number: 1, match_day: "Sat", date: "28-Mar-2026", time: "7:30 PM", stadium: "Bengaluru", match_name: "Royal Challengers Bengaluru vs Sunrisers Hyderabad" },
      { match_number: 2, match_day: "Sun", date: "29-Mar-2026", time: "7:30 PM", stadium: "Mumbai", match_name: "Mumbai Indians vs Kolkata Knight Riders" },
      { match_number: 3, match_day: "Mon", date: "30-Mar-2026", time: "7:30 PM", stadium: "Guwahati", match_name: "Rajasthan Royals vs Chennai Super Kings" },
      { match_number: 4, match_day: "Tue", date: "31-Mar-2026", time: "7:30 PM", stadium: "New Chandigarh", match_name: "Punjab Kings vs Gujarat Titans" },
      { match_number: 5, match_day: "Wed", date: "01-Apr-2026", time: "7:30 PM", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Delhi Capitals" },
      { match_number: 6, match_day: "Thu", date: "02-Apr-2026", time: "7:30 PM", stadium: "Kolkata", match_name: "Kolkata Knight Riders vs Sunrisers Hyderabad" },
      { match_number: 7, match_day: "Fri", date: "03-Apr-2026", time: "7:30 PM", stadium: "Chennai", match_name: "Chennai Super Kings vs Punjab Kings" },
      { match_number: 8, match_day: "Sat", date: "04-Apr-2026", time: "3:30 PM", stadium: "Delhi", match_name: "Delhi Capitals vs Mumbai Indians" },
      { match_number: 9, match_day: "Sat", date: "04-Apr-2026", time: "7:30 PM", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Rajasthan Royals" },
      { match_number: 10, match_day: "Sun", date: "05-Apr-2026", time: "3:30 PM", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Lucknow Super Giants" },
      { match_number: 11, match_day: "Sun", date: "05-Apr-2026", time: "7:30 PM", stadium: "Bengaluru", match_name: "Royal Challengers Bengaluru vs Chennai Super Kings" },
      { match_number: 12, match_day: "Mon", date: "06-Apr-2026", time: "7:30 PM", stadium: "Kolkata", match_name: "Kolkata Knight Riders vs Punjab Kings" },
      { match_number: 13, match_day: "Tue", date: "07-Apr-2026", time: "7:30 PM", stadium: "Guwahati", match_name: "Rajasthan Royals vs Mumbai Indians" },
      { match_number: 14, match_day: "Wed", date: "08-Apr-2026", time: "7:30 PM", stadium: "Delhi", match_name: "Delhi Capitals vs Gujarat Titans" },
      { match_number: 15, match_day: "Thu", date: "09-Apr-2026", time: "7:30 PM", stadium: "Kolkata", match_name: "Kolkata Knight Riders vs Lucknow Super Giants" },
      { match_number: 16, match_day: "Fri", date: "10-Apr-2026", time: "7:30 PM", stadium: "Guwahati", match_name: "Rajasthan Royals vs Royal Challengers Bengaluru" },
      { match_number: 17, match_day: "Sat", date: "11-Apr-2026", time: "3:30 PM", stadium: "New Chandigarh", match_name: "Punjab Kings vs Sunrisers Hyderabad" },
      { match_number: 18, match_day: "Sat", date: "11-Apr-2026", time: "7:30 PM", stadium: "Chennai", match_name: "Chennai Super Kings vs Delhi Capitals" },
      { match_number: 19, match_day: "Sun", date: "12-Apr-2026", time: "3:30 PM", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Gujarat Titans" },
      { match_number: 20, match_day: "Sun", date: "12-Apr-2026", time: "7:30 PM", stadium: "Mumbai", match_name: "Mumbai Indians vs Royal Challengers Bengaluru" },
      { match_number: 21, match_day: "Mon", date: "13-Apr-2026", time: "7:30 PM", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Rajasthan Royals" },
      { match_number: 22, match_day: "Tue", date: "14-Apr-2026", time: "7:30 PM", stadium: "Chennai", match_name: "Chennai Super Kings vs Kolkata Knight Riders" },
      { match_number: 23, match_day: "Wed", date: "15-Apr-2026", time: "7:30 PM", stadium: "Bengaluru", match_name: "Royal Challengers Bengaluru vs Lucknow Super Giants" },
      { match_number: 24, match_day: "Thu", date: "16-Apr-2026", time: "7:30 PM", stadium: "Mumbai", match_name: "Mumbai Indians vs Punjab Kings" },
      { match_number: 25, match_day: "Fri", date: "17-Apr-2026", time: "7:30 PM", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Kolkata Knight Riders" },
      { match_number: 26, match_day: "Sat", date: "18-Apr-2026", time: "3:30 PM", stadium: "Bengaluru", match_name: "Royal Challengers Bengaluru vs Delhi Capitals" },
      { match_number: 27, match_day: "Sat", date: "18-Apr-2026", time: "7:30 PM", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Chennai Super Kings" },
      { match_number: 28, match_day: "Sun", date: "19-Apr-2026", time: "3:30 PM", stadium: "Kolkata", match_name: "Kolkata Knight Riders vs Rajasthan Royals" },
      { match_number: 29, match_day: "Sun", date: "19-Apr-2026", time: "7:30 PM", stadium: "New Chandigarh", match_name: "Punjab Kings vs Lucknow Super Giants" },
      { match_number: 30, match_day: "Mon", date: "20-Apr-2026", time: "7:30 PM", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Mumbai Indians" },
      { match_number: 31, match_day: "Tue", date: "21-Apr-2026", time: "7:30 PM", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Delhi Capitals" },
      { match_number: 32, match_day: "Wed", date: "22-Apr-2026", time: "7:30 PM", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Rajasthan Royals" },
      { match_number: 33, match_day: "Thu", date: "23-Apr-2026", time: "7:30 PM", stadium: "Mumbai", match_name: "Mumbai Indians vs Chennai Super Kings" },
      { match_number: 34, match_day: "Fri", date: "24-Apr-2026", time: "7:30 PM", stadium: "Bengaluru", match_name: "Royal Challengers Bengaluru vs Gujarat Titans" },
      { match_number: 35, match_day: "Sat", date: "25-Apr-2026", time: "3:30 PM", stadium: "Delhi", match_name: "Delhi Capitals vs Punjab Kings" },
      { match_number: 36, match_day: "Sat", date: "25-Apr-2026", time: "7:30 PM", stadium: "Jaipur", match_name: "Rajasthan Royals vs Sunrisers Hyderabad" },
      { match_number: 37, match_day: "Sun", date: "26-Apr-2026", time: "3:30 PM", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Chennai Super Kings" },
      { match_number: 38, match_day: "Sun", date: "26-Apr-2026", time: "7:30 PM", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Kolkata Knight Riders" },
      { match_number: 39, match_day: "Mon", date: "27-Apr-2026", time: "7:30 PM", stadium: "Delhi", match_name: "Delhi Capitals vs Royal Challengers Bengaluru" },
      { match_number: 40, match_day: "Tue", date: "28-Apr-2026", time: "7:30 PM", stadium: "New Chandigarh", match_name: "Punjab Kings vs Rajasthan Royals" },
      { match_number: 41, match_day: "Wed", date: "29-Apr-2026", time: "7:30 PM", stadium: "Mumbai", match_name: "Mumbai Indians vs Sunrisers Hyderabad" },
      { match_number: 42, match_day: "Thu", date: "30-Apr-2026", time: "7:30 PM", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Royal Challengers Bengaluru" },
      { match_number: 43, match_day: "Fri", date: "01-May-2026", time: "7:30 PM", stadium: "Jaipur", match_name: "Rajasthan Royals vs Delhi Capitals" },
      { match_number: 44, match_day: "Sat", date: "02-May-2026", time: "7:30 PM", stadium: "Chennai", match_name: "Chennai Super Kings vs Mumbai Indians" },
      { match_number: 45, match_day: "Sun", date: "03-May-2026", time: "3:30 PM", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Kolkata Knight Riders" },
      { match_number: 46, match_day: "Sun", date: "03-May-2026", time: "7:30 PM", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Punjab Kings" },
      { match_number: 47, match_day: "Mon", date: "04-May-2026", time: "7:30 PM", stadium: "Mumbai", match_name: "Mumbai Indians vs Lucknow Super Giants" },
      { match_number: 48, match_day: "Tue", date: "05-May-2026", time: "7:30 PM", stadium: "Delhi", match_name: "Delhi Capitals vs Chennai Super Kings" },
      { match_number: 49, match_day: "Wed", date: "06-May-2026", time: "7:30 PM", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Punjab Kings" },
      { match_number: 50, match_day: "Thu", date: "07-May-2026", time: "7:30 PM", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Royal Challengers Bengaluru" },
      { match_number: 51, match_day: "Fri", date: "08-May-2026", time: "7:30 PM", stadium: "Delhi", match_name: "Delhi Capitals vs Kolkata Knight Riders" },
      { match_number: 52, match_day: "Sat", date: "09-May-2026", time: "7:30 PM", stadium: "Jaipur", match_name: "Rajasthan Royals vs Gujarat Titans" },
      { match_number: 53, match_day: "Sun", date: "10-May-2026", time: "3:30 PM", stadium: "Chennai", match_name: "Chennai Super Kings vs Lucknow Super Giants" },
      { match_number: 54, match_day: "Sun", date: "10-May-2026", time: "7:30 PM", stadium: "Raipur", match_name: "Royal Challengers Bengaluru vs Mumbai Indians" },
      { match_number: 55, match_day: "Mon", date: "11-May-2026", time: "7:30 PM", stadium: "Dharamshala", match_name: "Punjab Kings vs Delhi Capitals" },
      { match_number: 56, match_day: "Tue", date: "12-May-2026", time: "7:30 PM", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Sunrisers Hyderabad" },
      { match_number: 57, match_day: "Wed", date: "13-May-2026", time: "7:30 PM", stadium: "Raipur", match_name: "Royal Challengers Bengaluru vs Kolkata Knight Riders" },
      { match_number: 58, match_day: "Thu", date: "14-May-2026", time: "7:30 PM", stadium: "Dharamshala", match_name: "Punjab Kings vs Mumbai Indians" },
      { match_number: 59, match_day: "Fri", date: "15-May-2026", time: "7:30 PM", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Chennai Super Kings" },
      { match_number: 60, match_day: "Sat", date: "16-May-2026", time: "7:30 PM", stadium: "Kolkata", match_name: "Kolkata Knight Riders vs Gujarat Titans" },
      { match_number: 61, match_day: "Sun", date: "17-May-2026", time: "3:30 PM", stadium: "Dharamshala", match_name: "Punjab Kings vs Royal Challengers Bengaluru" },
      { match_number: 62, match_day: "Sun", date: "17-May-2026", time: "7:30 PM", stadium: "Delhi", match_name: "Delhi Capitals vs Rajasthan Royals" },
      { match_number: 63, match_day: "Mon", date: "18-May-2026", time: "7:30 PM", stadium: "Chennai", match_name: "Chennai Super Kings vs Sunrisers Hyderabad" },
      { match_number: 64, match_day: "Tue", date: "19-May-2026", time: "7:30 PM", stadium: "Jaipur", match_name: "Rajasthan Royals vs Lucknow Super Giants" },
      { match_number: 65, match_day: "Wed", date: "20-May-2026", time: "7:30 PM", stadium: "Kolkata", match_name: "Kolkata Knight Riders vs Mumbai Indians" },
      { match_number: 66, match_day: "Thu", date: "21-May-2026", time: "7:30 PM", stadium: "Chennai", match_name: "Chennai Super Kings vs Gujarat Titans" },
      { match_number: 67, match_day: "Fri", date: "22-May-2026", time: "7:30 PM", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Royal Challengers Bengaluru" },
      { match_number: 68, match_day: "Sat", date: "23-May-2026", time: "7:30 PM", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Punjab Kings" },
      { match_number: 69, match_day: "Sun", date: "24-May-2026", time: "3:30 PM", stadium: "Mumbai", match_name: "Mumbai Indians vs Rajasthan Royals" },
      { match_number: 70, match_day: "Sun", date: "24-May-2026", time: "7:30 PM", stadium: "Kolkata", match_name: "Kolkata Knight Riders vs Delhi Capitals" },
  ];
  T20_WORLDCUP_SCHEDULE = [
    { match_number: 1, match_name: 'Pakistan vs Netherlands', stadium: 'SSC Colombo, Colombo', match_date: '07-February-2026', match_time: '11:00 AM' },
    { match_number: 2, match_name: 'West Indies vs Scotland', stadium: 'Eden Gardens, Kolkata', match_date: '07-February-2026', match_time: '03:00 PM' },
    { match_number: 3, match_name: 'India vs USA', stadium: 'Wankhede Stadium, Mumbai', match_date: '07-February-2026', match_time: '07:00 PM' },
    { match_number: 4, match_name: 'New Zealand vs Afghanistan', stadium: 'MA Chidambaram Stadium, Chennai', match_date: '08-February-2026', match_time: '11:00 AM' },
    { match_number: 5, match_name: 'England vs Nepal', stadium: 'Wankhede Stadium, Mumbai', match_date: '08-February-2026', match_time: '03:00 PM' },
    { match_number: 6, match_name: 'Sri Lanka vs Ireland', stadium: 'R Premadasa Stadium, Colombo', match_date: '08-February-2026', match_time: '07:00 PM' },
    { match_number: 7, match_name: 'Scotland vs Italy', stadium: 'Eden Gardens, Kolkata', match_date: '09-February-2026', match_time: '11:00 AM' },
    { match_number: 8, match_name: 'Zimbabwe vs Oman', stadium: 'SSC Colombo, Colombo', match_date: '09-February-2026', match_time: '03:00 PM' },
    { match_number: 9, match_name: 'South Africa vs Canada', stadium: 'Narendra Modi Stadium, Ahmedabad', match_date: '09-February-2026', match_time: '07:00 PM' },
    { match_number: 10, match_name: 'Netherlands vs Namibia', stadium: 'Arun Jaitley Stadium, Delhi', match_date: '10-February-2026', match_time: '11:00 AM' },
    { match_number: 11, match_name: 'New Zealand vs UAE', stadium: 'MA Chidambaram Stadium, Chennai', match_date: '10-February-2026', match_time: '03:00 PM' },
    { match_number: 12, match_name: 'Pakistan vs USA', stadium: 'SSC Colombo, Colombo', match_date: '10-February-2026', match_time: '07:00 PM' },
    { match_number: 13, match_name: 'South Africa vs Afghanistan', stadium: 'Narendra Modi Stadium, Ahmedabad', match_date: '11-February-2026', match_time: '11:00 AM' },
    { match_number: 14, match_name: 'Australia vs Ireland', stadium: 'R Premadasa Stadium, Colombo', match_date: '11-February-2026', match_time: '03:00 PM' },
    { match_number: 15, match_name: 'England vs West Indies', stadium: 'Wankhede Stadium, Mumbai', match_date: '11-February-2026', match_time: '07:00 PM' },
    { match_number: 16, match_name: 'Sri Lanka vs Oman', stadium: 'Pallekele Stadium, Kandy', match_date: '12-February-2026', match_time: '11:00 AM' },
    { match_number: 17, match_name: 'Nepal vs Italy', stadium: 'Wankhede Stadium, Mumbai', match_date: '12-February-2026', match_time: '03:00 PM' },
    { match_number: 18, match_name: 'India vs Namibia', stadium: 'Arun Jaitley Stadium, Delhi', match_date: '12-February-2026', match_time: '07:00 PM' },
    { match_number: 19, match_name: 'Australia vs Zimbabwe', stadium: 'R Premadasa Stadium, Colombo', match_date: '13-February-2026', match_time: '11:00 AM' },
    { match_number: 20, match_name: 'Canada vs UAE', stadium: 'Arun Jaitley Stadium, Delhi', match_date: '13-February-2026', match_time: '03:00 PM' },
    { match_number: 21, match_name: 'USA vs Netherlands', stadium: 'MA Chidambaram Stadium, Chennai', match_date: '13-February-2026', match_time: '07:00 PM' },
    { match_number: 22, match_name: 'Ireland vs Oman', stadium: 'SSC Colombo, Colombo', match_date: '14-February-2026', match_time: '11:00 AM' },
    { match_number: 23, match_name: 'England vs Scotland', stadium: 'Eden Gardens, Kolkata', match_date: '14-February-2026', match_time: '03:00 PM' },
    { match_number: 24, match_name: 'New Zealand vs South Africa', stadium: 'Narendra Modi Stadium, Ahmedabad', match_date: '14-February-2026', match_time: '07:00 PM' },
    { match_number: 25, match_name: 'West Indies vs Nepal', stadium: 'Wankhede Stadium, Mumbai', match_date: '15-February-2026', match_time: '11:00 AM' },
    { match_number: 26, match_name: 'USA vs Namibia', stadium: 'MA Chidambaram Stadium, Chennai', match_date: '15-February-2026', match_time: '03:00 PM' },
    { match_number: 27, match_name: 'India vs Pakistan', stadium: 'R Premadasa Stadium, Colombo', match_date: '15-February-2026', match_time: '07:00 PM' },
    { match_number: 28, match_name: 'Afghanistan vs UAE', stadium: 'Arun Jaitley Stadium, Delhi', match_date: '16-February-2026', match_time: '11:00 AM' },
    { match_number: 29, match_name: 'England vs Italy', stadium: 'Eden Gardens, Kolkata', match_date: '16-February-2026', match_time: '03:00 PM' },
    { match_number: 30, match_name: 'Australia vs Sri Lanka', stadium: 'Pallekele Stadium, Kandy', match_date: '16-February-2026', match_time: '07:00 PM' },
    { match_number: 31, match_name: 'New Zealand vs Canada', stadium: 'MA Chidambaram Stadium, Chennai', match_date: '17-February-2026', match_time: '11:00 AM' },
    { match_number: 32, match_name: 'Ireland vs Zimbabwe', stadium: 'Pallekele Stadium, Kandy', match_date: '17-February-2026', match_time: '03:00 PM' },
    { match_number: 33, match_name: 'Scotland vs Nepal', stadium: 'Wankhede Stadium, Mumbai', match_date: '17-February-2026', match_time: '07:00 PM' },
    { match_number: 34, match_name: 'South Africa vs UAE', stadium: 'Arun Jaitley Stadium, Delhi', match_date: '18-February-2026', match_time: '11:00 AM' },
    { match_number: 35, match_name: 'Pakistan vs Namibia', stadium: 'SSC Colombo, Colombo', match_date: '18-February-2026', match_time: '03:00 PM' },
    { match_number: 36, match_name: 'India vs Netherlands', stadium: 'Narendra Modi Stadium, Ahmedabad', match_date: '18-February-2026', match_time: '07:00 PM' },
    { match_number: 37, match_name: 'West Indies vs Italy', stadium: 'Eden Gardens, Kolkata', match_date: '19-February-2026', match_time: '11:00 AM' },
    { match_number: 38, match_name: 'Sri Lanka vs Zimbabwe', stadium: 'R Premadasa Stadium, Colombo', match_date: '19-February-2026', match_time: '03:00 PM' },
    { match_number: 39, match_name: 'Afghanistan vs Canada', stadium: 'MA Chidambaram Stadium, Chennai', match_date: '19-February-2026', match_time: '07:00 PM' },
    { match_number: 40, match_name: 'Australia vs Oman', stadium: 'Pallekele Stadium, Kandy', match_date: '20-February-2026', match_time: '07:00 PM' },
    { match_number: 41, match_name: 'Super 8s Y2 vs Y3', stadium: 'R Premadasa Stadium, Colombo', match_date: '21-February-2026', match_time: '07:00 PM' },
    { match_number: 42, match_name: 'Super 8s Y1 vs Y4', stadium: 'Pallekele Stadium, Kandy', match_date: '22-February-2026', match_time: '03:00 PM' },
    { match_number: 43, match_name: 'Super 8s X1 vs X4', stadium: 'Narendra Modi Stadium, Ahmedabad', match_date: '22-February-2026', match_time: '07:00 PM' },
    { match_number: 44, match_name: 'Super 8s X2 vs X3', stadium: 'Wankhede Stadium, Mumbai', match_date: '23-February-2026', match_time: '07:00 PM' },
    { match_number: 45, match_name: 'Super 8s Y1 vs Y3', stadium: 'Pallekele Stadium, Kandy', match_date: '24-February-2026', match_time: '07:00 PM' },
    { match_number: 46, match_name: 'Super 8s Y2 vs Y4', stadium: 'R Premadasa Stadium, Colombo', match_date: '25-February-2026', match_time: '07:00 PM' },
    { match_number: 47, match_name: 'Super 8s X3 vs X4', stadium: 'Narendra Modi Stadium, Ahmedabad', match_date: '26-February-2026', match_time: '03:00 PM' },
    { match_number: 48, match_name: 'Super 8s X1 vs X2', stadium: 'MA Chidambaram Stadium, Chennai', match_date: '26-February-2026', match_time: '07:00 PM' },
    { match_number: 49, match_name: 'Super 8s Y1 vs Y2', stadium: 'R Premadasa Stadium, Colombo', match_date: '27-February-2026', match_time: '07:00 PM' },
    { match_number: 50, match_name: 'Super 8s Y3 vs Y4', stadium: 'Pallekele Stadium, Kandy', match_date: '28-February-2026', match_time: '07:00 PM' },
    { match_number: 51, match_name: 'Super 8s X2 vs X4', stadium: 'Arun Jaitley Stadium, Delhi', match_date: '01-March-2026', match_time: '03:00 PM' },
    { match_number: 52, match_name: 'Super 8s X1 vs X3', stadium: 'Eden Gardens, Kolkata', match_date: '01-March-2026', match_time: '07:00 PM' },
    { match_number: 53, match_name: 'Semi-final 1: Winner A vs Winner B', stadium: 'Eden Gardens, Kolkata / R Premadasa Stadium, Colombo', match_date: '04-March-2026', match_time: '07:00 PM' },
    { match_number: 54, match_name: 'Semi-final 2: Winner C vs Winner D', stadium: 'Wankhede Stadium, Mumbai', match_date: '05-March-2026', match_time: '07:00 PM' },
    { match_number: 55, match_name: 'Final: Semi-final Winner 1 vs Semi-final Winner 2', stadium: 'Narendra Modi Stadium, Ahmedabad / R Premadasa Stadium, Colombo', match_date: '08-March-2026', match_time: '07:00 PM' }
  ].freeze


  CT_2025_SCHEDULE = [
    { match_number: 1, match_name: 'Pakistan vs New Zealand', stadium: 'Karachi, Pakistan', match_date: '19-February-2025' },
    { match_number: 2, match_name: 'Bangladesh vs India', stadium: 'Dubai', match_date: '20-February-2025' },
    { match_number: 3, match_name: 'Afghanistan vs South Africa', stadium: 'Karachi, Pakistan', match_date: '21-February-2025' },
    { match_number: 4, match_name: 'Australia vs England', stadium: 'Lahore, Pakistan', match_date: '22-February-2025' },
    { match_number: 5, match_name: 'Pakistan vs India', stadium: 'Dubai', match_date: '23-February-2025' },
    { match_number: 6, match_name: 'Bangladesh vs New Zealand', stadium: 'Rawalpindi, Pakistan', match_date: '24-February-2025' },
    { match_number: 7, match_name: 'Australia vs South Africa', stadium: 'Rawalpindi, Pakistan', match_date: '25-February-2025' },
    { match_number: 8, match_name: 'Afghanistan vs England', stadium: 'Lahore, Pakistan', match_date: '26-February-2025' },
    { match_number: 9, match_name: 'Pakistan vs Bangladesh', stadium: 'Rawalpindi, Pakistan', match_date: '27-February-2025' },
    { match_number: 10, match_name: 'Afghanistan vs Australia', stadium: 'Lahore, Pakistan', match_date: '28-February-2025' },
    { match_number: 11, match_name: 'South Africa vs England', stadium: 'Karachi, Pakistan', match_date: '01-March-2025' },
    { match_number: 12, match_name: 'New Zealand vs India', stadium: 'Dubai', match_date: '02-March-2025' },
    { match_number: 13, match_name: 'Semi-final 1', stadium: 'Dubai', match_date: '04-March-2025' },
    { match_number: 14, match_name: 'Semi-final 2', stadium: 'Lahore, Pakistan', match_date: '05-March-2025' },
    { match_number: 15, match_name: 'Final', stadium: 'Lahore (or Dubai)', match_date: '09-March-2025' }
  ]
end
