# frozen_string_literal: true
module Schedule

  IPL_SCHEDULE = [
    { match_number: 1, match_day: "Sat", date: "22-Mar-2025", stadium: "Kolkata", match_name: "Kolkata Knight Riders vs Royal Challengers Bengaluru" },
    { match_number: 2, match_day: "Sun", date: "23-Mar-2025", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Rajasthan Royals" },
    { match_number: 3, match_day: "Sun", date: "23-Mar-2025", stadium: "Chennai", match_name: "Chennai Super Kings vs Mumbai Indians" },
    { match_number: 4, match_day: "Mon", date: "24-Mar-2025", stadium: "Visakhapatnam", match_name: "Delhi Capitals vs Lucknow Super Giants" },
    { match_number: 5, match_day: "Tue", date: "25-Mar-2025", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Punjab Kings" },
    { match_number: 6, match_day: "Wed", date: "26-Mar-2025", stadium: "Guwahati", match_name: "Rajasthan Royals vs Kolkata Knight Riders" },
    { match_number: 7, match_day: "Thu", date: "27-Mar-2025", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Lucknow Super Giants" },
    { match_number: 8, match_day: "Fri", date: "28-Mar-2025", stadium: "Chennai", match_name: "Chennai Super Kings vs Royal Challengers Bengaluru" },
    { match_number: 9, match_day: "Sat", date: "29-Mar-2025", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Mumbai Indians" },
    { match_number: 10, match_day: "Sun", date: "30-Mar-2025", stadium: "Visakhapatnam", match_name: "Delhi Capitals vs Sunrisers Hyderabad" },
    { match_number: 11, match_day: "Sun", date: "30-Mar-2025", stadium: "Guwahati", match_name: "Rajasthan Royals vs Punjab Kings" },
    { match_number: 12, match_day: "Mon", date: "31-Mar-2025", stadium: "Mumbai", match_name: "Mumbai Indians vs Kolkata Knight Riders" },
    { match_number: 13, match_day: "Tue", date: "01-Apr-2025", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Gujarat Titans" },
    { match_number: 14, match_day: "Wed", date: "02-Apr-2025", stadium: "Bengaluru", match_name: "Royal Challengers Bengaluru vs Delhi Capitals" },
    { match_number: 15, match_day: "Thu", date: "03-Apr-2025", stadium: "Kolkata", match_name: "Kolkata Knight Riders vs Chennai Super Kings" },
    { match_number: 16, match_day: "Fri", date: "04-Apr-2025", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Rajasthan Royals" },
    { match_number: 17, match_day: "Sat", date: "05-Apr-2025", stadium: "Chennai", match_name: "Chennai Super Kings vs Punjab Kings" },
    { match_number: 18, match_day: "Sat", date: "05-Apr-2025", stadium: "New Chandigarh", match_name: "Punjab Kings vs Mumbai Indians" },
    { match_number: 19, match_day: "Sun", date: "06-Apr-2025", stadium: "Kolkata", match_name: "Kolkata Knight Riders vs Delhi Capitals" },
    { match_number: 20, match_day: "Sun", date: "06-Apr-2025", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Gujarat Titans" },
    { match_number: 21, match_day: "Mon", date: "07-Apr-2025", stadium: "Mumbai", match_name: "Mumbai Indians vs Royal Challengers Bengaluru" },
    { match_number: 22, match_day: "Tue", date: "08-Apr-2025", stadium: "New Chandigarh", match_name: "Punjab Kings vs Rajasthan Royals" },
    { match_number: 23, match_day: "Wed", date: "09-Apr-2025", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Delhi Capitals" },
    { match_number: 24, match_day: "Thu", date: "10-Apr-2025", stadium: "Bengaluru", match_name: "Royal Challengers Bengaluru vs Lucknow Super Giants" },
    { match_number: 25, match_day: "Fri", date: "11-Apr-2025", stadium: "Chennai", match_name: "Chennai Super Kings vs Sunrisers Hyderabad" },
    { match_number: 26, match_day: "Sat", date: "12-Apr-2025", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Mumbai Indians" },
    { match_number: 27, match_day: "Sat", date: "12-Apr-2025", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Rajasthan Royals" },
    { match_number: 28, match_day: "Sun", date: "13-Apr-2025", stadium: "Jaipur", match_name: "Rajasthan Royals vs Delhi Capitals" },
    { match_number: 29, match_day: "Sun", date: "13-Apr-2025", stadium: "Delhi", match_name: "Delhi Capitals vs Kolkata Knight Riders" },
    { match_number: 30, match_day: "Mon", date: "14-Apr-2025", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Punjab Kings" },
    { match_number: 31, match_day: "Tue", date: "15-Apr-2025", stadium: "Delhi", match_name: "Delhi Capitals vs Mumbai Indians" },
    { match_number: 32, match_day: "Wed", date: "16-Apr-2025", stadium: "Mumbai", match_name: "Mumbai Indians vs Royal Challengers Bengaluru" },
    { match_number: 33, match_day: "Thu", date: "17-Apr-2025", stadium: "Bengaluru", match_name: "Royal Challengers Bengaluru vs Gujarat Titans" },
    { match_number: 34, match_day: "Fri", date: "18-Apr-2025", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Rajasthan Royals" },
    { match_number: 35, match_day: "Sat", date: "19-Apr-2025", stadium: "Jaipur", match_name: "Rajasthan Royals vs Punjab Kings" },
    { match_number: 36, match_day: "Sat", date: "19-Apr-2025", stadium: "New Chandigarh", match_name: "Punjab Kings vs Delhi Capitals" },
    { match_number: 37, match_day: "Sun", date: "20-Apr-2025", stadium: "Delhi", match_name: "Delhi Capitals vs Lucknow Super Giants" },
    { match_number: 38, match_day: "Sun", date: "20-Apr-2025", stadium: "Mumbai", match_name: "Mumbai Indians vs Kolkata Knight Riders" },
    { match_number: 39, match_day: "Tue", date: "22-Apr-2025", stadium: "Kolkata", match_name: "Kolkata Knight Riders vs Chennai Super Kings" },
    { match_number: 40, match_day: "Wed", date: "23-Apr-2025", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Gujarat Titans" },
    { match_number: 41, match_day: "Fri", date: "25-Apr-2025", stadium: "Bengaluru", match_name: "Royal Challengers Bengaluru vs Mumbai Indians" },
    { match_number: 42, match_day: "Sat", date: "26-Apr-2025", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Punjab Kings" },
    { match_number: 43, match_day: "Sun", date: "27-Apr-2025", stadium: "New Chandigarh", match_name: "Punjab Kings vs Rajasthan Royals" },
    { match_number: 44, match_day: "Sun", date: "27-Apr-2025", stadium: "Delhi", match_name: "Delhi Capitals vs Kolkata Knight Riders" },
    { match_number: 45, match_day: "Tue", date: "29-Apr-2025", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Mumbai Indians" },
    { match_number: 46, match_day: "Wed", date: "30-Apr-2025", stadium: "Chennai", match_name: "Chennai Super Kings vs Sunrisers Hyderabad" },
    { match_number: 47, match_day: "Fri", date: "02-May-2025", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Rajasthan Royals" },
    { match_number: 48, match_day: "Sat", date: "03-May-2025", stadium: "Mumbai", match_name: "Mumbai Indians vs Royal Challengers Bengaluru" },
    { match_number: 49, match_day: "Sun", date: "04-May-2025", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Delhi Capitals" },
    { match_number: 50, match_day: "Sun", date: "04-May-2025", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Punjab Kings" },
    { match_number: 51, match_day: "Tue", date: "06-May-2025", stadium: "Delhi", match_name: "Delhi Capitals vs Chennai Super Kings" },
    { match_number: 52, match_day: "Wed", date: "07-May-2025", stadium: "Kolkata", match_name: "Kolkata Knight Riders vs Rajasthan Royals" },
    { match_number: 53, match_day: "Fri", date: "09-May-2025", stadium: "New Chandigarh", match_name: "Punjab Kings vs Mumbai Indians" },
    { match_number: 54, match_day: "Sat", date: "10-May-2025", stadium: "Jaipur", match_name: "Rajasthan Royals vs Royal Challengers Bengaluru" },
    { match_number: 55, match_day: "Sun", date: "11-May-2025", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Sunrisers Hyderabad" },
    { match_number: 56, match_day: "Sun", date: "11-May-2025", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Kolkata Knight Riders" },
    { match_number: 57, match_day: "Tue", date: "13-May-2025", stadium: "Delhi", match_name: "Delhi Capitals vs Punjab Kings" },
    { match_number: 58, match_day: "Wed", date: "14-May-2025", stadium: "Mumbai", match_name: "Mumbai Indians vs Gujarat Titans" },
    { match_number: 59, match_day: "Fri", date: "16-May-2025", stadium: "Chennai", match_name: "Chennai Super Kings vs Lucknow Super Giants" },
    { match_number: 60, match_day: "Sat", date: "17-May-2025", stadium: "Hyderabad", match_name: "Sunrisers Hyderabad vs Delhi Capitals" },
    { match_number: 61, match_day: "Sun", date: "18-May-2025", stadium: "Bengaluru", match_name: "Royal Challengers Bengaluru vs Kolkata Knight Riders" },
    { match_number: 62, match_day: "Sun", date: "18-May-2025", stadium: "Ahmedabad", match_name: "Gujarat Titans vs Rajasthan Royals" },
    { match_number: 63, match_day: "Tue", date: "20-May-2025", stadium: "Lucknow", match_name: "Lucknow Super Giants vs Sunrisers Hyderabad" },
    { match_number: 64, match_day: "Wed", date: "21-May-2025", stadium: "New Chandigarh", match_name: "Punjab Kings vs Chennai Super Kings" },
    { match_number: 65, match_day: "Fri", date: "23-May-2025", stadium: "Mumbai", match_name: "Mumbai Indians vs Delhi Capitals" },
    { match_number: 66, match_day: "Sun", date: "25-May-2025", stadium: "Ahmedabad", match_name: "Qualifier 1" },
    { match_number: 67, match_day: "Sun", date: "25-May-2025", stadium: "Kolkata", match_name: "Eliminator" },
    { match_number: 68, match_day: "Tue", date: "27-May-2025", stadium: "Chennai", match_name: "Qualifier 2" },
    { match_number: 69, match_day: "Fri", date: "30-May-2025", stadium: "Ahmedabad", match_name: "Final" }
  ].freeze

  T20_WORLDCUP_SCHEDULE = [
    { match_number: 1, match_name: 'USA vs Canada', stadium: 'Dallas', match_date: '02-June-2024',
      time: '6 AM' },
    { match_number: 2, match_name: 'West Indies vs Papua New Guinea', stadium: 'Guyana',
      match_date: '02-June-2024', time: '8 PM' },
    { match_number: 3, match_name: 'Namibia vs Oman', stadium: 'Barbados', match_date: '03-June-2024',
      time: '6 AM' },
    { match_number: 4, match_name: 'Sri Lanka vs South Africa', stadium: 'New York', match_date: '03-June-2024',
      time: '8 PM' },
    { match_number: 5, match_name: 'Afghanistan vs Uganda', stadium: 'Guyana', match_date: '04-June-2024',
      time: '6 AM' },
    { match_number: 6, match_name: 'England vs Scotland', stadium: 'Barbados', match_date: '04-June-2024',
      time: '8 PM' },
    { match_number: 7, match_name: 'Netherlands vs Nepal', stadium: 'Dallas', match_date: '04-June-2024',
      time: '9 PM' },
    { match_number: 8, match_name: 'India vs Ireland', stadium: 'New York', match_date: '05-June-2024',
      time: '8 PM' },
    { match_number: 9, match_name: 'Papua New Guinea vs Uganda', stadium: 'Guyana', match_date: '06-June-2024',
      time: '5 AM' },
    { match_number: 10, match_name: 'Australia vs Oman', stadium: 'Barbados', match_date: '06-June-2024',
      time: '6 AM' },
    { match_number: 11, match_name: 'USA vs Pakistan', stadium: 'Dallas', match_date: '06-June-2024',
      time: '9 PM' },
    { match_number: 12, match_name: 'Namibia vs Scotland', stadium: 'Barbados', match_date: '07-June-2024',
      time: '12:30 AM' },
    { match_number: 13, match_name: 'Canada vs Ireland', stadium: 'New York', match_date: '07-June-2024',
      time: '8 PM' },
    { match_number: 14, match_name: 'New Zealand vs Afghanistan', stadium: 'Guyana', match_date: '08-June-2024',
      time: '5 AM' },
    { match_number: 15, match_name: 'Sri Lanka vs Bangladesh', stadium: 'Dallas', match_date: '08-June-2024',
      time: '6 AM' },
    { match_number: 16, match_name: 'Netherlands vs South Africa', stadium: 'New York',
      match_date: '08-June-2024', time: '8 PM' },
    { match_number: 17, match_name: 'Australia vs England', stadium: 'Barbados', match_date: '08-June-2024',
      time: '10:30 PM' },
    { match_number: 18, match_name: 'West Indies vs Uganda', stadium: 'Guyana', match_date: '09-June-2024',
      time: '6 AM' },
    { match_number: 19, match_name: 'India vs Pakistan', stadium: 'New York', match_date: '09-June-2024',
      time: '8 PM' },
    { match_number: 20, match_name: 'Oman vs Scotland', stadium: 'Antigua', match_date: '09-June-2024',
      time: '10:30 PM' },
    { match_number: 21, match_name: 'South Africa vs Bangladesh', stadium: 'New York',
      match_date: '10-June-2024', time: '8 PM' },
    { match_number: 22, match_name: 'Pakistan vs Canada', stadium: 'New York', match_date: '11-June-2024',
      time: '8 PM' },
    { match_number: 23, match_name: 'Sri Lanka vs Nepal', stadium: 'Florida', match_date: '12-June-2024',
      time: '5 AM' },
    { match_number: 24, match_name: 'Australia vs Namibia', stadium: 'Antigua', match_date: '12-June-2024',
      time: '6 AM' },
    { match_number: 25, match_name: 'USA vs India', stadium: 'New York', match_date: '12-June-2024',
      time: '8 PM' },
    { match_number: 26, match_name: 'West Indies vs New Zealand', stadium: 'Trinidad & Tobago',
      match_date: '13-June-2024', time: '6 AM' },
    { match_number: 27, match_name: 'Bangladesh vs Netherlands', stadium: 'St Vincent',
      match_date: '13-June-2024', time: '8 PM' },
    { match_number: 28, match_name: 'England vs Oman', stadium: 'Antigua', match_date: '14-June-2024',
      time: '12:30 AM' },
    { match_number: 29, match_name: 'Afghanistan vs Papua New Guinea', stadium: 'Trinidad & Tobago',
      match_date: '14-June-2024', time: '6 AM' },
    { match_number: 30, match_name: 'USA vs Ireland', stadium: 'Florida', match_date: '14-June-2024',
      time: '8 PM' },
    { match_number: 31, match_name: 'South Africa vs Nepal', stadium: 'St Vincent', match_date: '15-June-2024',
      time: '5 AM' },
    { match_number: 32, match_name: 'New Zealand vs Uganda', stadium: 'Trinidad & Tobago',
      match_date: '15-June-2024', time: '6 AM' },
    { match_number: 33, match_name: 'India vs Canada', stadium: 'Florida', match_date: '15-June-2024',
      time: '8 PM' },
    { match_number: 34, match_name: 'Namibia vs England', stadium: 'Antigua', match_date: '15-June-2024',
      time: '10:30 PM' },
    { match_number: 35, match_name: 'Australia vs Scotland', stadium: 'St Lucia', match_date: '16-June-2024',
      time: '6 AM' },
    { match_number: 36, match_name: 'Pakistan vs Ireland', stadium: 'Florida', match_date: '16-June-2024',
      time: '8 PM' },
    { match_number: 37, match_name: 'Bangladesh vs Nepal', stadium: 'St Vincent', match_date: '17-June-2024',
      time: '5 AM' },
    { match_number: 38, match_name: 'Sri Lanka vs Netherlands', stadium: 'St Lucia', match_date: '17-June-2024',
      time: '6 AM' },
    { match_number: 39, match_name: 'New Zealand vs Papua New Guinea', stadium: 'Trinidad & Tobago',
      match_date: '17-June-2024', time: '8 PM' },
    { match_number: 40, match_name: 'West Indies vs Afghanistan', stadium: 'St Lucia',
      match_date: '18-June-2024', time: '6 AM' },
    { match_number: 41, match_name: 'SA vs USA ', stadium: 'Antigua', match_date: '19-June-2024', time: '8 PM' },
    { match_number: 42, match_name: 'WI vs ENG ', stadium: 'St Lucia', match_date: '20-June-2024', time: '6 AM' },
    { match_number: 43, match_name: 'IND vs AFG', stadium: 'Barbados', match_date: '20-June-2024', time: '8 PM' },
    { match_number: 44, match_name: 'AUS vs BANG', stadium: 'Antigua', match_date: '21-June-2024', time: '6 AM' },
    { match_number: 45, match_name: 'ENG vs SA', stadium: 'St Lucia', match_date: '21-June-2024', time: '8 PM' },
    { match_number: 46, match_name: 'USA vs WI', stadium: 'Barbados', match_date: '22-June-2024', time: '6 AM' },
    { match_number: 47, match_name: 'IND vs BANG', stadium: 'Antigua', match_date: '22-June-2024', time: '8 PM' },
    { match_number: 48, match_name: 'AFG vs AUS', stadium: 'St Vincent', match_date: '23-June-2024',
      time: '6 AM' },
    { match_number: 49, match_name: 'USA vs ENG', stadium: 'Barbados', match_date: '23-June-2024', time: '8 PM' },
    { match_number: 50, match_name: 'WI vs SA', stadium: 'Antigua', match_date: '24-June-2024', time: '6 AM' },
    { match_number: 51, match_name: 'AUS vs IND', stadium: 'St Lucia', match_date: '24-June-2024', time: '8 PM' },
    { match_number: 52, match_name: 'AFG vs BANG', stadium: 'St Vincent', match_date: '25-June-2024',
      time: '6 AM' },
    { match_number: 53, match_name: '1st Semi-Final', stadium: 'Trinidad & Tobago', match_date: '27-June-2024',
      time: '6 AM' },
    { match_number: 54, match_name: '2nd Semi-Final', stadium: 'Guyana', match_date: '27-June-2024',
      time: '8 PM' },
    { match_number: 55, match_name: 'Final', stadium: 'Barbados', match_date: '29-June-2024', time: '8 PM' }
  ].freeze


  CT_2025_SCHEDULE = [
    { match_number: 1, match_name: 'Pakistan vs New Zealand', stadium: 'Karachi, Pakistan', match_date: '19-February-2025' },
    { match_number: 2, match_name: 'Bangladesh vs India', stadium: 'Dubai', match_date: '20-February-2025' },
    { match_number: 3, match_name: 'Afghanistan vs South Africa', stadium: 'Karachi, Pakistan', match_date: '21-February-2025' },
    { match_number: 4, match_name: 'Australia vs England', stadium: 'Lahore, Pakistan', match_date: '22-February-2025' },
    { match_number: 5, match_name: 'Pakistan vs India', stadium: 'Dubai', match_date: '23-February-2025' },
    { match_number: 6, match_name: 'Bangladesh vs New Zealand', stadium: 'Rawalpindi, Pakistan', match_date: '24-February-2025' },
    { match_number: 7, match_name: 'Australia vs South Africa', stadium: 'Rawalpindi, Pakistan', match_date: '25-February-2025' },
    { match_number: 8, match_name: 'Afghanistan vs England', stadium: 'Lahore, Pakistan', match_date: '26-February-2025' },
    { match_number: 9, match_name: 'Pakistan vs Bangladesh', stadium: 'Rawalpindi, Pakistan', match_date: '27-February-2025' },
    { match_number: 10, match_name: 'Afghanistan vs Australia', stadium: 'Lahore, Pakistan', match_date: '28-February-2025' },
    { match_number: 11, match_name: 'South Africa vs England', stadium: 'Karachi, Pakistan', match_date: '01-March-2025' },
    { match_number: 12, match_name: 'New Zealand vs India', stadium: 'Dubai', match_date: '02-March-2025' },
    { match_number: 13, match_name: 'Semi-final 1', stadium: 'Dubai', match_date: '04-March-2025' },
    { match_number: 14, match_name: 'Semi-final 2', stadium: 'Lahore, Pakistan', match_date: '05-March-2025' },
    { match_number: 15, match_name: 'Final', stadium: 'Lahore (or Dubai)', match_date: '09-March-2025' }
  ]
end
