# frozen_string_literal: true

module Responses
  class ScorecardResponse
    def self.demo_series_res
      SERIES.with_indifferent_access
    end

    def self.demo_res
      RES.with_indifferent_access
    end

    # RES = {
    #   scoreCard: [
    #     {
    #       matchId: 101_626,
    #       inningsId: 1,
    #       timeScore: 1_735_202_518_000,
    #       batTeamDetails: {
    #         batTeamId: 196,
    #         batTeamName: 'Melbourne Renegades',
    #         batTeamShortName: 'MR',
    #         batsmenData: {
    #           bat_1: {
    #             batId: 8502,
    #             batName: 'Duckett',
    #             batShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 68,
    #             balls: 29,
    #             dots: 0,
    #             fours: 10,
    #             sixes: 2,
    #             mins: 0,
    #             strikeRate: 234.48,
    #             outDesc: 'c T Murphy b Jackson Bird',
    #             bowlerId: 8165,
    #             fielderId1: 15_146,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 10,
    #             sixers: 2,
    #             wicketCode: 'CAUGHT',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_2: {
    #             batId: 23_186,
    #             batName: 'Thomas Rogers',
    #             batShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 12,
    #             balls: 6,
    #             dots: 0,
    #             fours: 1,
    #             sixes: 1,
    #             mins: 0,
    #             strikeRate: 200.0,
    #             outDesc: 'c J Vince b Akeal Hosein',
    #             bowlerId: 8435,
    #             fielderId1: 6642,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 1,
    #             sixers: 1,
    #             wicketCode: 'CAUGHT',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_3: {
    #             batId: 10_979,
    #             batName: 'Sam Harper',
    #             batShortName: '',
    #             isCaptain: false,
    #             isKeeper: true,
    #             runs: 12,
    #             balls: 12,
    #             dots: 0,
    #             fours: 1,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 100.0,
    #             outDesc: 'c Hayden Kerr b T Murphy',
    #             bowlerId: 15_146,
    #             fielderId1: 15_783,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 1,
    #             sixers: 0,
    #             wicketCode: 'CAUGHT',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_4: {
    #             batId: 7662,
    #             batName: 'Maxwell',
    #             batShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 32,
    #             balls: 17,
    #             dots: 0,
    #             fours: 2,
    #             sixes: 3,
    #             mins: 0,
    #             strikeRate: 188.24,
    #             outDesc: 'c T Murphy b Dwarshuis',
    #             bowlerId: 9739,
    #             fielderId1: 15_146,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 2,
    #             sixers: 3,
    #             wicketCode: 'CAUGHT',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_5: {
    #             batId: 8989,
    #             batName: 'Stoinis',
    #             batShortName: '',
    #             isCaptain: true,
    #             isKeeper: false,
    #             runs: 20,
    #             balls: 19,
    #             dots: 0,
    #             fours: 3,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 105.26,
    #             outDesc: 'b T Murphy',
    #             bowlerId: 15_146,
    #             fielderId1: 0,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 3,
    #             sixers: 0,
    #             wicketCode: 'BOWLED',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_6: {
    #             batId: 8876,
    #             batName: 'Cartwright',
    #             batShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 15,
    #             balls: 11,
    #             dots: 0,
    #             fours: 2,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 136.36,
    #             outDesc: 'c Philippe b Dwarshuis',
    #             bowlerId: 9739,
    #             fielderId1: 13_172,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 2,
    #             sixers: 0,
    #             wicketCode: 'CAUGHT',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_7: {
    #             batId: 9522,
    #             batName: 'Tom Curran',
    #             batShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 15,
    #             balls: 14,
    #             dots: 0,
    #             fours: 1,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 107.14,
    #             outDesc: 'c Silk b Jackson Bird',
    #             bowlerId: 8165,
    #             fielderId1: 8645,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 1,
    #             sixers: 0,
    #             wicketCode: 'CAUGHT',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_8: {
    #             batId: 13_122,
    #             batName: 'Jonathan Merlo',
    #             batShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 8,
    #             balls: 6,
    #             dots: 0,
    #             fours: 1,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 133.33,
    #             outDesc: 'not out',
    #             bowlerId: 0,
    #             fielderId1: 0,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 1,
    #             sixers: 0,
    #             wicketCode: '',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: 'IN'
    #           },
    #           bat_9: {
    #             batId: 11_318,
    #             batName: 'Usama Mir',
    #             batShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 2,
    #             balls: 2,
    #             dots: 0,
    #             fours: 0,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 100.0,
    #             outDesc: 'c Jack Edwards b Jackson Bird',
    #             bowlerId: 8165,
    #             fielderId1: 13_348,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 0,
    #             sixers: 0,
    #             wicketCode: 'CAUGHT',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: 'IN'
    #           },
    #           bat_10: {
    #             batId: 51_921,
    #             batName: 'Doug Warren',
    #             batShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 3,
    #             balls: 4,
    #             dots: 0,
    #             fours: 0,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 75.0,
    #             outDesc: 'b Hayden Kerr',
    #             bowlerId: 15_783,
    #             fielderId1: 0,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 0,
    #             sixers: 0,
    #             wicketCode: 'BOWLED',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_11: {
    #             batId: 1444,
    #             batName: 'Siddle',
    #             batShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 0,
    #             balls: 0,
    #             dots: 0,
    #             fours: 0,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 0.0,
    #             outDesc: '',
    #             bowlerId: 0,
    #             fielderId1: 0,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 0,
    #             sixers: 0,
    #             wicketCode: '',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           }
    #         }
    #       },
    #       bowlTeamDetails: {
    #         bowlTeamId: 198,
    #         bowlTeamName: 'Sydney Sixers',
    #         bowlTeamShortName: 'SYS',
    #         bowlersData: {
    #           bowl_1: {
    #             bowlerId: 8165,
    #             bowlName: 'Jackson Bird',
    #             bowlShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             overs: 3.0,
    #             maidens: 0,
    #             runs: 35,
    #             wickets: 3,
    #             economy: 11.7,
    #             no_balls: 0,
    #             wides: 0,
    #             dots: 0,
    #             balls: 0,
    #             runsPerBall: 0.0,
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: 'IN'
    #           },
    #           bowl_2: {
    #             bowlerId: 8435,
    #             bowlName: 'Akeal Hosein',
    #             bowlShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             overs: 4.0,
    #             maidens: 0,
    #             runs: 50,
    #             wickets: 1,
    #             economy: 12.5,
    #             no_balls: 0,
    #             wides: 0,
    #             dots: 0,
    #             balls: 0,
    #             runsPerBall: 0.0,
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bowl_3: {
    #             bowlerId: 9739,
    #             bowlName: 'Dwarshuis',
    #             bowlShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             overs: 4.0,
    #             maidens: 0,
    #             runs: 33,
    #             wickets: 2,
    #             economy: 8.2,
    #             no_balls: 0,
    #             wides: 3,
    #             dots: 0,
    #             balls: 0,
    #             runsPerBall: 0.0,
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bowl_4: {
    #             bowlerId: 15_146,
    #             bowlName: 'T Murphy',
    #             bowlShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             overs: 4.0,
    #             maidens: 0,
    #             runs: 26,
    #             wickets: 2,
    #             economy: 6.5,
    #             no_balls: 0,
    #             wides: 0,
    #             dots: 0,
    #             balls: 0,
    #             runsPerBall: 0.0,
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bowl_5: {
    #             bowlerId: 13_348,
    #             bowlName: 'Jack Edwards',
    #             bowlShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             overs: 1.0,
    #             maidens: 0,
    #             runs: 5,
    #             wickets: 0,
    #             economy: 5.0,
    #             no_balls: 0,
    #             wides: 0,
    #             dots: 0,
    #             balls: 0,
    #             runsPerBall: 0.0,
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bowl_6: {
    #             bowlerId: 15_783,
    #             bowlName: 'Hayden Kerr',
    #             bowlShortName: '',
    #             isCaptain: false,
    #             isKeeper: false,
    #             overs: 4.0,
    #             maidens: 0,
    #             runs: 41,
    #             wickets: 1,
    #             economy: 10.2,
    #             no_balls: 0,
    #             wides: 0,
    #             dots: 0,
    #             balls: 0,
    #             runsPerBall: 0.0,
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: 'IN'
    #           }
    #         }
    #       },
    #       scoreDetails: {
    #         ballNbr: 120,
    #         isDeclared: false,
    #         isFollowOn: false,
    #         overs: 20.0,
    #         revisedOvers: 0.0,
    #         runRate: 9.7,
    #         runs: 194,
    #         wickets: 9,
    #         runsPerBall: 0.97
    #       },
    #       extrasData: {
    #         noBalls: 0,
    #         total: 7,
    #         byes: 2,
    #         penalty: 0,
    #         wides: 3,
    #         legByes: 2
    #       },
    #       ppData: {
    #         pp_1: {
    #           ppId: 1,
    #           ppOversFrom: 0.1,
    #           ppOversTo: 4.0,
    #           ppType: 'mandatory',
    #           runsScored: 57
    #         },
    #         pp_2: {
    #           ppId: 2,
    #           ppOversFrom: 10.1,
    #           ppOversTo: 12.0,
    #           ppType: 'batting',
    #           runsScored: 16
    #         }
    #       },
    #       wicketsData: {
    #         wkt_1: {
    #           batId: 23_186,
    #           batName: 'Thomas Rogers',
    #           wktNbr: 1,
    #           wktOver: 1.4,
    #           wktRuns: 16,
    #           ballNbr: 14
    #         },
    #         wkt_2: {
    #           batId: 10_979,
    #           batName: 'Sam Harper',
    #           wktNbr: 2,
    #           wktOver: 6.5,
    #           wktRuns: 77,
    #           ballNbr: 65
    #         },
    #         wkt_3: {
    #           batId: 8502,
    #           batName: 'Duckett',
    #           wktNbr: 3,
    #           wktOver: 8.4,
    #           wktRuns: 106,
    #           ballNbr: 84
    #         },
    #         wkt_4: {
    #           batId: 7662,
    #           batName: 'Maxwell',
    #           wktNbr: 4,
    #           wktOver: 11.6,
    #           wktRuns: 132,
    #           ballNbr: 116
    #         },
    #         wkt_5: {
    #           batId: 8989,
    #           batName: 'Stoinis',
    #           wktNbr: 5,
    #           wktOver: 14.1,
    #           wktRuns: 150,
    #           ballNbr: 141
    #         },
    #         wkt_6: {
    #           batId: 8876,
    #           batName: 'Cartwright',
    #           wktNbr: 6,
    #           wktOver: 17.2,
    #           wktRuns: 178,
    #           ballNbr: 172
    #         },
    #         wkt_7: {
    #           batId: 9522,
    #           batName: 'Tom Curran',
    #           wktNbr: 7,
    #           wktOver: 18.2,
    #           wktRuns: 183,
    #           ballNbr: 182
    #         },
    #         wkt_8: {
    #           batId: 11_318,
    #           batName: 'Usama Mir',
    #           wktNbr: 8,
    #           wktOver: 18.4,
    #           wktRuns: 185,
    #           ballNbr: 184
    #         },
    #         wkt_9: {
    #           batId: 51_921,
    #           batName: 'Doug Warren',
    #           wktNbr: 9,
    #           wktOver: 19.6,
    #           wktRuns: 194,
    #           ballNbr: 196
    #         }
    #       },
    #       partnershipsData: {
    #         pat_1: {
    #           bat1Id: 8502,
    #           bat1Name: 'Duckett',
    #           bat1Runs: 4,
    #           bat1fours: 0,
    #           bat1sixes: 0,
    #           bat2Id: 23_186,
    #           bat2Name: 'Thomas Rogers',
    #           bat2Runs: 12,
    #           bat2fours: 1,
    #           bat2sixes: 1,
    #           totalRuns: 16,
    #           totalBalls: 10,
    #           bat1balls: 0,
    #           bat2balls: 0,
    #           bat1Ones: 0,
    #           bat1Twos: 0,
    #           bat1Threes: 0,
    #           bat1Fives: 0,
    #           bat1Boundaries: 0,
    #           bat1Sixers: 0,
    #           bat2Ones: 0,
    #           bat2Twos: 0,
    #           bat2Threes: 0,
    #           bat2Fives: 0,
    #           bat2Boundaries: 0,
    #           bat2Sixers: 0
    #         },
    #         pat_2: {
    #           bat1Id: 8502,
    #           bat1Name: 'Duckett',
    #           bat1Runs: 47,
    #           bat1fours: 8,
    #           bat1sixes: 1,
    #           bat2Id: 10_979,
    #           bat2Name: 'Sam Harper',
    #           bat2Runs: 12,
    #           bat2fours: 1,
    #           bat2sixes: 0,
    #           totalRuns: 61,
    #           totalBalls: 31,
    #           bat1balls: 0,
    #           bat2balls: 0,
    #           bat1Ones: 0,
    #           bat1Twos: 0,
    #           bat1Threes: 0,
    #           bat1Fives: 0,
    #           bat1Boundaries: 0,
    #           bat1Sixers: 0,
    #           bat2Ones: 0,
    #           bat2Twos: 0,
    #           bat2Threes: 0,
    #           bat2Fives: 0,
    #           bat2Boundaries: 0,
    #           bat2Sixers: 0
    #         },
    #         pat_3: {
    #           bat1Id: 8502,
    #           bat1Name: 'Duckett',
    #           bat1Runs: 17,
    #           bat1fours: 2,
    #           bat1sixes: 1,
    #           bat2Id: 7662,
    #           bat2Name: 'Maxwell',
    #           bat2Runs: 12,
    #           bat2fours: 1,
    #           bat2sixes: 1,
    #           totalRuns: 29,
    #           totalBalls: 11,
    #           bat1balls: 0,
    #           bat2balls: 0,
    #           bat1Ones: 0,
    #           bat1Twos: 0,
    #           bat1Threes: 0,
    #           bat1Fives: 0,
    #           bat1Boundaries: 0,
    #           bat1Sixers: 0,
    #           bat2Ones: 0,
    #           bat2Twos: 0,
    #           bat2Threes: 0,
    #           bat2Fives: 0,
    #           bat2Boundaries: 0,
    #           bat2Sixers: 0
    #         },
    #         pat_4: {
    #           bat1Id: 8989,
    #           bat1Name: 'Stoinis',
    #           bat1Runs: 3,
    #           bat1fours: 0,
    #           bat1sixes: 0,
    #           bat2Id: 7662,
    #           bat2Name: 'Maxwell',
    #           bat2Runs: 20,
    #           bat2fours: 1,
    #           bat2sixes: 2,
    #           totalRuns: 26,
    #           totalBalls: 20,
    #           bat1balls: 0,
    #           bat2balls: 0,
    #           bat1Ones: 0,
    #           bat1Twos: 0,
    #           bat1Threes: 0,
    #           bat1Fives: 0,
    #           bat1Boundaries: 0,
    #           bat1Sixers: 0,
    #           bat2Ones: 0,
    #           bat2Twos: 0,
    #           bat2Threes: 0,
    #           bat2Fives: 0,
    #           bat2Boundaries: 0,
    #           bat2Sixers: 0
    #         },
    #         pat_5: {
    #           bat1Id: 8989,
    #           bat1Name: 'Stoinis',
    #           bat1Runs: 17,
    #           bat1fours: 3,
    #           bat1sixes: 0,
    #           bat2Id: 8876,
    #           bat2Name: 'Cartwright',
    #           bat2Runs: 1,
    #           bat2fours: 0,
    #           bat2sixes: 0,
    #           totalRuns: 18,
    #           totalBalls: 13,
    #           bat1balls: 0,
    #           bat2balls: 0,
    #           bat1Ones: 0,
    #           bat1Twos: 0,
    #           bat1Threes: 0,
    #           bat1Fives: 0,
    #           bat1Boundaries: 0,
    #           bat1Sixers: 0,
    #           bat2Ones: 0,
    #           bat2Twos: 0,
    #           bat2Threes: 0,
    #           bat2Fives: 0,
    #           bat2Boundaries: 0,
    #           bat2Sixers: 0
    #         },
    #         pat_6: {
    #           bat1Id: 9522,
    #           bat1Name: 'Tom Curran',
    #           bat1Runs: 13,
    #           bat1fours: 1,
    #           bat1sixes: 0,
    #           bat2Id: 8876,
    #           bat2Name: 'Cartwright',
    #           bat2Runs: 14,
    #           bat2fours: 2,
    #           bat2sixes: 0,
    #           totalRuns: 28,
    #           totalBalls: 19,
    #           bat1balls: 0,
    #           bat2balls: 0,
    #           bat1Ones: 0,
    #           bat1Twos: 0,
    #           bat1Threes: 0,
    #           bat1Fives: 0,
    #           bat1Boundaries: 0,
    #           bat1Sixers: 0,
    #           bat2Ones: 0,
    #           bat2Twos: 0,
    #           bat2Threes: 0,
    #           bat2Fives: 0,
    #           bat2Boundaries: 0,
    #           bat2Sixers: 0
    #         },
    #         pat_7: {
    #           bat1Id: 9522,
    #           bat1Name: 'Tom Curran',
    #           bat1Runs: 2,
    #           bat1fours: 0,
    #           bat1sixes: 0,
    #           bat2Id: 13_122,
    #           bat2Name: 'Merlo',
    #           bat2Runs: 2,
    #           bat2fours: 0,
    #           bat2sixes: 0,
    #           totalRuns: 5,
    #           totalBalls: 6,
    #           bat1balls: 0,
    #           bat2balls: 0,
    #           bat1Ones: 0,
    #           bat1Twos: 0,
    #           bat1Threes: 0,
    #           bat1Fives: 0,
    #           bat1Boundaries: 0,
    #           bat1Sixers: 0,
    #           bat2Ones: 0,
    #           bat2Twos: 0,
    #           bat2Threes: 0,
    #           bat2Fives: 0,
    #           bat2Boundaries: 0,
    #           bat2Sixers: 0
    #         },
    #         pat_8: {
    #           bat1Id: 11_318,
    #           bat1Name: 'Usama Mir',
    #           bat1Runs: 2,
    #           bat1fours: 0,
    #           bat1sixes: 0,
    #           bat2Id: 13_122,
    #           bat2Name: 'Merlo',
    #           bat2Runs: 0,
    #           bat2fours: 0,
    #           bat2sixes: 0,
    #           totalRuns: 2,
    #           totalBalls: 2,
    #           bat1balls: 0,
    #           bat2balls: 0,
    #           bat1Ones: 0,
    #           bat1Twos: 0,
    #           bat1Threes: 0,
    #           bat1Fives: 0,
    #           bat1Boundaries: 0,
    #           bat1Sixers: 0,
    #           bat2Ones: 0,
    #           bat2Twos: 0,
    #           bat2Threes: 0,
    #           bat2Fives: 0,
    #           bat2Boundaries: 0,
    #           bat2Sixers: 0
    #         },
    #         pat_9: {
    #           bat1Id: 51_921,
    #           bat1Name: 'Doug Warren',
    #           bat1Runs: 3,
    #           bat1fours: 0,
    #           bat1sixes: 0,
    #           bat2Id: 13_122,
    #           bat2Name: 'Merlo',
    #           bat2Runs: 6,
    #           bat2fours: 1,
    #           bat2sixes: 0,
    #           totalRuns: 9,
    #           totalBalls: 8,
    #           bat1balls: 0,
    #           bat2balls: 0,
    #           bat1Ones: 0,
    #           bat1Twos: 0,
    #           bat1Threes: 0,
    #           bat1Fives: 0,
    #           bat1Boundaries: 0,
    #           bat1Sixers: 0,
    #           bat2Ones: 0,
    #           bat2Twos: 0,
    #           bat2Threes: 0,
    #           bat2Fives: 0,
    #           bat2Boundaries: 0,
    #           bat2Sixers: 0
    #         }
    #       }
    #     },
    #     {
    #       matchId: 101_626,
    #       inningsId: 2,
    #       timeScore: 1_735_208_352_000,
    #       batTeamDetails: {
    #         batTeamId: 198,
    #         batTeamName: 'Perth Scorchers',
    #         batTeamShortName: 'PS',
    #         batsmenData: {
    #           bat_1: {
    #             batId: 13_172,
    #             batName: 'Josh Philippe',
    #             batShortName: 'Philippe',
    #             isCaptain: false,
    #             isKeeper: true,
    #             runs: 42,
    #             balls: 23,
    #             dots: 6,
    #             fours: 4,
    #             sixes: 2,
    #             mins: 31,
    #             strikeRate: 182.61,
    #             outDesc: 'c Duckett b Tom Curran',
    #             bowlerId: 9522,
    #             fielderId1: 8502,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 9,
    #             twos: 1,
    #             threes: 1,
    #             fives: 0,
    #             boundaries: 4,
    #             sixers: 2,
    #             wicketCode: 'CAUGHT',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_2: {
    #             batId: 6642,
    #             batName: 'James Vince',
    #             batShortName: 'J Vince',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 101,
    #             balls: 58,
    #             dots: 18,
    #             fours: 12,
    #             sixes: 4,
    #             mins: 82,
    #             strikeRate: 174.14,
    #             outDesc: 'not out',
    #             bowlerId: 0,
    #             fielderId1: 0,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 20,
    #             twos: 3,
    #             threes: 1,
    #             fives: 0,
    #             boundaries: 12,
    #             sixers: 4,
    #             wicketCode: '',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_3: {
    #             batId: 1437,
    #             batName: 'Moises Henriques',
    #             batShortName: 'Henriques',
    #             isCaptain: true,
    #             isKeeper: false,
    #             runs: 11,
    #             balls: 9,
    #             dots: 4,
    #             fours: 2,
    #             sixes: 0,
    #             mins: 12,
    #             strikeRate: 122.22,
    #             outDesc: 'c Duckett b Usama Mir',
    #             bowlerId: 11_318,
    #             fielderId1: 8502,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 3,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 2,
    #             sixers: 0,
    #             wicketCode: 'CAUGHT',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_4: {
    #             batId: 8645,
    #             batName: 'Jordan Silk',
    #             batShortName: 'Silk',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 34,
    #             balls: 19,
    #             dots: 3,
    #             fours: 3,
    #             sixes: 1,
    #             mins: 36,
    #             strikeRate: 178.95,
    #             outDesc: 'not out',
    #             bowlerId: 0,
    #             fielderId1: 0,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 9,
    #             twos: 2,
    #             threes: 1,
    #             fives: 0,
    #             boundaries: 3,
    #             sixers: 1,
    #             wicketCode: '',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_5: {
    #             batId: 13_348,
    #             batName: 'Jack Edwards',
    #             batShortName: 'Jack Edwards',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 0,
    #             balls: 0,
    #             dots: 0,
    #             fours: 0,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 0.0,
    #             outDesc: '',
    #             bowlerId: 0,
    #             fielderId1: 0,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 0,
    #             sixers: 0,
    #             wicketCode: '',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_6: {
    #             batId: 23_446,
    #             batName: 'Lachlan Shaw',
    #             batShortName: 'Lachlan Shaw',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 0,
    #             balls: 0,
    #             dots: 0,
    #             fours: 0,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 0.0,
    #             outDesc: '',
    #             bowlerId: 0,
    #             fielderId1: 0,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 0,
    #             sixers: 0,
    #             wicketCode: '',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_7: {
    #             batId: 15_783,
    #             batName: 'Hayden Kerr',
    #             batShortName: 'Hayden Kerr',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 0,
    #             balls: 0,
    #             dots: 0,
    #             fours: 0,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 0.0,
    #             outDesc: '',
    #             bowlerId: 0,
    #             fielderId1: 0,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 0,
    #             sixers: 0,
    #             wicketCode: '',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: 'IN'
    #           },
    #           bat_8: {
    #             batId: 9739,
    #             batName: 'Ben Dwarshuis',
    #             batShortName: 'Dwarshuis',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 0,
    #             balls: 0,
    #             dots: 0,
    #             fours: 0,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 0.0,
    #             outDesc: '',
    #             bowlerId: 0,
    #             fielderId1: 0,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 0,
    #             sixers: 0,
    #             wicketCode: '',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_9: {
    #             batId: 8435,
    #             batName: 'Akeal Hosein',
    #             batShortName: 'Akeal Hosein',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 0,
    #             balls: 0,
    #             dots: 0,
    #             fours: 0,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 0.0,
    #             outDesc: '',
    #             bowlerId: 0,
    #             fielderId1: 0,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 0,
    #             sixers: 0,
    #             wicketCode: '',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_10: {
    #             batId: 15_146,
    #             batName: 'Todd Murphy',
    #             batShortName: 'T Murphy',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 0,
    #             balls: 0,
    #             dots: 0,
    #             fours: 0,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 0.0,
    #             outDesc: '',
    #             bowlerId: 0,
    #             fielderId1: 0,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 0,
    #             sixers: 0,
    #             wicketCode: '',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bat_11: {
    #             batId: 8165,
    #             batName: 'Jackson Bird',
    #             batShortName: 'Jackson Bird',
    #             isCaptain: false,
    #             isKeeper: false,
    #             runs: 0,
    #             balls: 0,
    #             dots: 0,
    #             fours: 0,
    #             sixes: 0,
    #             mins: 0,
    #             strikeRate: 0.0,
    #             outDesc: '',
    #             bowlerId: 0,
    #             fielderId1: 0,
    #             fielderId2: 0,
    #             fielderId3: 0,
    #             ones: 0,
    #             twos: 0,
    #             threes: 0,
    #             fives: 0,
    #             boundaries: 0,
    #             sixers: 0,
    #             wicketCode: '',
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: 'IN'
    #           }
    #         }
    #       },
    #       bowlTeamDetails: {
    #         bowlTeamId: 196,
    #         bowlTeamName: 'Melbourne Stars',
    #         bowlTeamShortName: 'MLS',
    #         bowlersData: {
    #           bowl_1: {
    #             bowlerId: 7662,
    #             bowlName: 'Glenn Maxwell',
    #             bowlShortName: 'Maxwell',
    #             isCaptain: false,
    #             isKeeper: false,
    #             overs: 2.0,
    #             maidens: 0,
    #             runs: 31,
    #             wickets: 0,
    #             economy: 15.5,
    #             no_balls: 0,
    #             wides: 0,
    #             dots: 0,
    #             balls: 0,
    #             runsPerBall: 0.0,
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bowl_2: {
    #             bowlerId: 1444,
    #             bowlName: 'Peter Siddle',
    #             bowlShortName: 'Siddle',
    #             isCaptain: false,
    #             isKeeper: false,
    #             overs: 3.0,
    #             maidens: 0,
    #             runs: 21,
    #             wickets: 0,
    #             economy: 7.0,
    #             no_balls: 0,
    #             wides: 1,
    #             dots: 0,
    #             balls: 0,
    #             runsPerBall: 0.0,
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bowl_3: {
    #             bowlerId: 8989,
    #             bowlName: 'Marcus Stoinis',
    #             bowlShortName: 'Stoinis',
    #             isCaptain: true,
    #             isKeeper: false,
    #             overs: 4.0,
    #             maidens: 0,
    #             runs: 38,
    #             wickets: 0,
    #             economy: 9.5,
    #             no_balls: 0,
    #             wides: 6,
    #             dots: 0,
    #             balls: 0,
    #             runsPerBall: 0.0,
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bowl_4: {
    #             bowlerId: 9522,
    #             bowlName: 'Tom Curran',
    #             bowlShortName: 'Tom Curran',
    #             isCaptain: false,
    #             isKeeper: false,
    #             overs: 3.0,
    #             maidens: 0,
    #             runs: 39,
    #             wickets: 1,
    #             economy: 13.0,
    #             no_balls: 0,
    #             wides: 1,
    #             dots: 0,
    #             balls: 0,
    #             runsPerBall: 0.0,
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           },
    #           bowl_5: {
    #             bowlerId: 11_318,
    #             bowlName: 'Usama Mir',
    #             bowlShortName: 'Usama Mir',
    #             isCaptain: false,
    #             isKeeper: false,
    #             overs: 4.0,
    #             maidens: 0,
    #             runs: 43,
    #             wickets: 1,
    #             economy: 10.8,
    #             no_balls: 0,
    #             wides: 0,
    #             dots: 0,
    #             balls: 0,
    #             runsPerBall: 0.0,
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: 'IN'
    #           },
    #           bowl_6: {
    #             bowlerId: 51_921,
    #             bowlName: 'Doug Warren',
    #             bowlShortName: 'Doug Warren',
    #             isCaptain: false,
    #             isKeeper: false,
    #             overs: 2.1,
    #             maidens: 0,
    #             runs: 24,
    #             wickets: 0,
    #             economy: 11.1,
    #             no_balls: 0,
    #             wides: 0,
    #             dots: 0,
    #             balls: 0,
    #             runsPerBall: 0.0,
    #             isOverseas: false,
    #             inMatchChange: '',
    #             playingXIChange: ''
    #           }
    #         }
    #       },
    #       scoreDetails: {
    #         ballNbr: 109,
    #         isDeclared: false,
    #         isFollowOn: false,
    #         overs: 18.1,
    #         revisedOvers: 0.0,
    #         runRate: 10.9,
    #         runs: 198,
    #         wickets: 2,
    #         runsPerBall: 1.09
    #       },
    #       extrasData: {
    #         noBalls: 0,
    #         total: 10,
    #         byes: 0,
    #         penalty: 0,
    #         wides: 8,
    #         legByes: 2
    #       },
    #       ppData: {
    #         pp_1: {
    #           ppId: 3,
    #           ppOversFrom: 0.1,
    #           ppOversTo: 4.0,
    #           ppType: 'mandatory',
    #           runsScored: 35
    #         },
    #         pp_2: {
    #           ppId: 4,
    #           ppOversFrom: 13.1,
    #           ppOversTo: 15.0,
    #           ppType: 'batting',
    #           runsScored: 35
    #         }
    #       },
    #       wicketsData: {
    #         wkt_1: {
    #           batId: 13_172,
    #           batName: 'Josh Philippe',
    #           wktNbr: 1,
    #           wktOver: 7.6,
    #           wktRuns: 83,
    #           ballNbr: 76
    #         },
    #         wkt_2: {
    #           batId: 1437,
    #           batName: 'Moises Henriques',
    #           wktNbr: 2,
    #           wktOver: 10.4,
    #           wktRuns: 99,
    #           ballNbr: 104
    #         }
    #       },
    #       partnershipsData: {
    #         pat_1: {
    #           bat1Id: 13_172,
    #           bat1Name: 'Philippe',
    #           bat1Runs: 42,
    #           bat1fours: 4,
    #           bat1sixes: 2,
    #           bat2Id: 6642,
    #           bat2Name: 'James Vince',
    #           bat2Runs: 35,
    #           bat2fours: 5,
    #           bat2sixes: 1,
    #           totalRuns: 83,
    #           totalBalls: 48,
    #           bat1balls: 23,
    #           bat2balls: 25,
    #           bat1Ones: 9,
    #           bat1Twos: 1,
    #           bat1Threes: 1,
    #           bat1Fives: 0,
    #           bat1Boundaries: 4,
    #           bat1Sixers: 2,
    #           bat2Ones: 9,
    #           bat2Twos: 0,
    #           bat2Threes: 0,
    #           bat2Fives: 0,
    #           bat2Boundaries: 5,
    #           bat2Sixers: 1
    #         },
    #         pat_2: {
    #           bat1Id: 1437,
    #           bat1Name: 'Henriques',
    #           bat1Runs: 11,
    #           bat1fours: 2,
    #           bat1sixes: 0,
    #           bat2Id: 6642,
    #           bat2Name: 'James Vince',
    #           bat2Runs: 3,
    #           bat2fours: 0,
    #           bat2sixes: 0,
    #           totalRuns: 16,
    #           totalBalls: 16,
    #           bat1balls: 9,
    #           bat2balls: 7,
    #           bat1Ones: 3,
    #           bat1Twos: 0,
    #           bat1Threes: 0,
    #           bat1Fives: 0,
    #           bat1Boundaries: 2,
    #           bat1Sixers: 0,
    #           bat2Ones: 3,
    #           bat2Twos: 0,
    #           bat2Threes: 0,
    #           bat2Fives: 0,
    #           bat2Boundaries: 0,
    #           bat2Sixers: 0
    #         },
    #         pat_3: {
    #           bat1Id: 8645,
    #           bat1Name: 'Silk',
    #           bat1Runs: 34,
    #           bat1fours: 3,
    #           bat1sixes: 1,
    #           bat2Id: 6642,
    #           bat2Name: 'James Vince',
    #           bat2Runs: 63,
    #           bat2fours: 7,
    #           bat2sixes: 3,
    #           totalRuns: 99,
    #           totalBalls: 45,
    #           bat1balls: 19,
    #           bat2balls: 26,
    #           bat1Ones: 9,
    #           bat1Twos: 2,
    #           bat1Threes: 1,
    #           bat1Fives: 0,
    #           bat1Boundaries: 3,
    #           bat1Sixers: 1,
    #           bat2Ones: 8,
    #           bat2Twos: 3,
    #           bat2Threes: 1,
    #           bat2Fives: 0,
    #           bat2Boundaries: 7,
    #           bat2Sixers: 3
    #         }
    #       }
    #     }
    #   ],
    #   matchHeader: {
    #     matchId: 101_626,
    #     matchDescription: '11th Match',
    #     matchFormat: 'T20',
    #     matchType: 'league',
    #     complete: true,
    #     domestic: false,
    #     matchStartTimestamp: 1_735_196_700_000,
    #     matchCompleteTimestamp: 1_735_208_386_432,
    #     dayNight: false,
    #     year: 2024,
    #     state: 'Complete',
    #     status: 'Sydney Sixers won by 8 wkts',
    #     tossResults: {
    #       tossWinnerId: 198,
    #       tossWinnerName: 'Sydney Sixers',
    #       decision: 'Bowling'
    #     },
    #     result: {
    #       resultType: 'win',
    #       winningTeam: 'Sydney Sixers',
    #       winningteamId: 198,
    #       winningMargin: 8,
    #       winByRuns: false,
    #       winByInnings: false
    #     },
    #     revisedTarget: {
    #       reason: ''
    #     },
    #     playersOfTheMatch: [
    #       {
    #         id: 6642,
    #         name: 'J Vince',
    #         fullName: 'James Vince',
    #         nickName: 'James Vince',
    #         captain: false,
    #         keeper: false,
    #         substitute: false,
    #         teamName: 'Hampshire',
    #         faceImageId: 577_867
    #       }
    #     ],
    #     playersOfTheSeries: [],
    #     matchTeamInfo: [
    #       {
    #         battingTeamId: 196,
    #         battingTeamShortName: 'MLS',
    #         bowlingTeamId: 198,
    #         bowlingTeamShortName: 'SYS'
    #       },
    #       {
    #         battingTeamId: 198,
    #         battingTeamShortName: 'SYS',
    #         bowlingTeamId: 196,
    #         bowlingTeamShortName: 'MLS'
    #       }
    #     ],
    #     isMatchNotCovered: false,
    #     team1: {
    #       id: 198,
    #       name: 'Sydney Sixers',
    #       playerDetails: [],
    #       shortName: 'SYS'
    #     },
    #     team2: {
    #       id: 196,
    #       name: 'Melbourne Stars',
    #       playerDetails: [],
    #       shortName: 'MLS'
    #     },
    #     seriesDesc: 'Big Bash League 2024-25',
    #     seriesId: 8535,
    #     seriesName: 'Big Bash League 2024-25',
    #     alertType: 'auto',
    #     livestreamEnabled: false
    #   },
    #   isMatchComplete: true,
    #   status: 'Sydney Sixers won by 8 wkts',
    #   videos: [],
    #   responseLastUpdated: 1_735_288_967
    # }.freeze #this is res of match 101626

    RES =  {
      "scoreCard"=>[{"matchId"=>101617, "inningsId"=>1, "timeScore"=>1734947330000, "batTeamDetails"=>{"batTeamId"=>197, "batTeamName"=>"Perth Scorchers", "batTeamShortName"=>"PRS", "batsmenData"=>{"bat_1"=>{"batId"=>11172, "batName"=>"Finn Allen", "batShortName"=>"", "isCaptain"=>false, "isKeeper"=>false, "runs"=>0, "balls"=>3, "dots"=>0, "fours"=>0, "sixes"=>0, "mins"=>0, "strikeRate"=>0.0, "outDesc"=>"c Tom Rogers b Fergus O Neill", "bowlerId"=>24541, "fielderId1"=>13126, "fielderId2"=>0, "fielderId3"=>0, "ones"=>0, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>0, "sixers"=>0, "wicketCode"=>"CAUGHT", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_2"=>{"batId"=>9330, "batName"=>"Jennings", "batShortName"=>"", "isCaptain"=>false, "isKeeper"=>false, "runs"=>9, "balls"=>12, "dots"=>0, "fours"=>1, "sixes"=>0, "mins"=>0, "strikeRate"=>75.0, "outDesc"=>"run out (Mackenzie Harvey)", "bowlerId"=>0, "fielderId1"=>13472, "fielderId2"=>0, "fielderId3"=>0, "ones"=>0, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>1, "sixers"=>0, "wicketCode"=>"RUNOUT", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_3"=>{"batId"=>15927, "batName"=>"Cooper Connolly", "batShortName"=>"", "isCaptain"=>false, "isKeeper"=>false, "runs"=>66, "balls"=>50, "dots"=>0, "fours"=>1, "sixes"=>6, "mins"=>0, "strikeRate"=>132.0, "outDesc"=>"c Mackenzie Harvey b Zampa", "bowlerId"=>8642, "fielderId1"=>13472, "fielderId2"=>0, "fielderId3"=>0, "ones"=>0, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>1, "sixers"=>6, "wicketCode"=>"CAUGHT", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_4"=>{"batId"=>10637, "batName"=>"Josh Inglis", "batShortName"=>"", "isCaptain"=>false, "isKeeper"=>true, "runs"=>4, "balls"=>6, "dots"=>0, "fours"=>0, "sixes"=>0, "mins"=>0, "strikeRate"=>66.67, "outDesc"=>"c Jake Fraser-McGurk b Sutherland", "bowlerId"=>12229, "fielderId1"=>14501, "fielderId2"=>0, "fielderId3"=>0, "ones"=>0, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>0, "sixers"=>0, "wicketCode"=>"CAUGHT", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_5"=>{"batId"=>8506, "batName"=>"Turner", "batShortName"=>"", "isCaptain"=>true, "isKeeper"=>false, "runs"=>8, "balls"=>8, "dots"=>0, "fours"=>1, "sixes"=>0, "mins"=>0, "strikeRate"=>100.0, "outDesc"=>"b Tom Rogers", "bowlerId"=>13126, "fielderId1"=>0, "fielderId2"=>0, "fielderId3"=>0, "ones"=>0, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>1, "sixers"=>0, "wicketCode"=>"BOWLED", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_6"=>{"batId"=>15758, "batName"=>"Matthew Spoors", "batShortName"=>"", "isCaptain"=>false, "isKeeper"=>false, "runs"=>29, "balls"=>26, "dots"=>0, "fours"=>1, "sixes"=>2, "mins"=>0, "strikeRate"=>111.54, "outDesc"=>"c Mackenzie Harvey b Kane Richardson", "bowlerId"=>6262, "fielderId1"=>13472, "fielderId2"=>0, "fielderId3"=>0, "ones"=>0, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>1, "sixers"=>2, "wicketCode"=>"CAUGHT", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>"IN"}, "bat_7"=>{"batId"=>11049, "batName"=>"Nick Hobson", "batShortName"=>"", "isCaptain"=>false, "isKeeper"=>false, "runs"=>8, "balls"=>7, "dots"=>0, "fours"=>1, "sixes"=>0, "mins"=>0, "strikeRate"=>114.29, "outDesc"=>"c Sutherland b Tom Rogers", "bowlerId"=>13126, "fielderId1"=>12229, "fielderId2"=>0, "fielderId3"=>0, "ones"=>0, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>1, "sixers"=>0, "wicketCode"=>"CAUGHT", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_8"=>{"batId"=>8508, "batName"=>"Agar", "batShortName"=>"", "isCaptain"=>false, "isKeeper"=>false, "runs"=>3, "balls"=>4, "dots"=>0, "fours"=>0, "sixes"=>0, "mins"=>0, "strikeRate"=>75.0, "outDesc"=>"c Laurie Evans b Tom Rogers", "bowlerId"=>13126, "fielderId1"=>6531, "fielderId2"=>0, "fielderId3"=>0, "ones"=>0, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>0, "sixers"=>0, "wicketCode"=>"CAUGHT", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_9"=>{"batId"=>9451, "batName"=>"Matthew Kelly", "batShortName"=>"", "isCaptain"=>false, "isKeeper"=>false, "runs"=>2, "balls"=>1, "dots"=>0, "fours"=>0, "sixes"=>0, "mins"=>0, "strikeRate"=>200.0, "outDesc"=>"not out", "bowlerId"=>0, "fielderId1"=>0, "fielderId2"=>0, "fielderId3"=>0, "ones"=>0, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>0, "sixers"=>0, "wicketCode"=>"", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>"IN"}, "bat_10"=>{"batId"=>9617, "batName"=>"Andrew Tye", "batShortName"=>"", "isCaptain"=>false, "isKeeper"=>false, "runs"=>4, "balls"=>3, "dots"=>0, "fours"=>0, "sixes"=>0, "mins"=>0, "strikeRate"=>133.33, "outDesc"=>"not out", "bowlerId"=>0, "fielderId1"=>0, "fielderId2"=>0, "fielderId3"=>0, "ones"=>0, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>0, "sixers"=>0, "wicketCode"=>"", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>"IN"}, "bat_11"=>{"batId"=>7773, "batName"=>"Behrendorff", "batShortName"=>"", "isCaptain"=>false, "isKeeper"=>false, "runs"=>0, "balls"=>0, "dots"=>0, "fours"=>0, "sixes"=>0, "mins"=>0, "strikeRate"=>0.0, "outDesc"=>"", "bowlerId"=>0, "fielderId1"=>0, "fielderId2"=>0, "fielderId3"=>0, "ones"=>0, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>0, "sixers"=>0, "wicketCode"=>"", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}}}, "bowlTeamDetails"=>{"bowlTeamId"=>195, "bowlTeamName"=>"Melbourne Renegades", "bowlTeamShortName"=>"MLR", "bowlersData"=>{"bowl_1"=>{"bowlerId"=>24541, "bowlName"=>"Fergus O Neill", "bowlShortName"=>"", "isCaptain"=>false, "isKeeper"=>false, "overs"=>4.0, "maidens"=>1, "runs"=>18, "wickets"=>1, "economy"=>4.5, "no_balls"=>0, "wides"=>0, "dots"=>0, "balls"=>0, "runsPerBall"=>0.0, "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bowl_2"=>{"bowlerId"=>13126, "bowlName"=>"Tom Rogers", "bowlShortName"=>"", "isCaptain"=>false, "isKeeper"=>false, "overs"=>4.0, "maidens"=>0, "runs"=>22, "wickets"=>3, "economy"=>5.5, "no_balls"=>0, "wides"=>0, "dots"=>0, "balls"=>0, "runsPerBall"=>0.0, "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bowl_3"=>{"bowlerId"=>6262, "bowlName"=>"Kane Richardson", "bowlShortName"=>"", "isCaptain"=>false, "isKeeper"=>false, "overs"=>4.0, "maidens"=>0, "runs"=>39, "wickets"=>1, "economy"=>9.8, "no_balls"=>0, "wides"=>1, "dots"=>0, "balls"=>0, "runsPerBall"=>0.0, "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bowl_4"=>{"bowlerId"=>12229, "bowlName"=>"Sutherland", "bowlShortName"=>"", "isCaptain"=>true, "isKeeper"=>false, "overs"=>4.0, "maidens"=>0, "runs"=>27, "wickets"=>1, "economy"=>6.8, "no_balls"=>0, "wides"=>1, "dots"=>0, "balls"=>0, "runsPerBall"=>0.0, "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bowl_5"=>{"bowlerId"=>8642, "bowlName"=>"Zampa", "bowlShortName"=>"", "isCaptain"=>false, "isKeeper"=>false, "overs"=>4.0, "maidens"=>0, "runs"=>29, "wickets"=>1, "economy"=>7.2, "no_balls"=>0, "wides"=>0, "dots"=>0, "balls"=>0, "runsPerBall"=>0.0, "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}}}, "scoreDetails"=>{"ballNbr"=>120, "isDeclared"=>false, "isFollowOn"=>false, "overs"=>20.0, "revisedOvers"=>0.0, "runRate"=>7.15, "runs"=>143, "wickets"=>8, "runsPerBall"=>0.72}, "extrasData"=>{"noBalls"=>0, "total"=>10, "byes"=>0, "penalty"=>0, "wides"=>2, "legByes"=>8}, "ppData"=>{"pp_1"=>{"ppId"=>3, "ppOversFrom"=>0.1, "ppOversTo"=>4.0, "ppType"=>"mandatory", "runsScored"=>12}, "pp_2"=>{"ppId"=>4, "ppOversFrom"=>15.1, "ppOversTo"=>17.0, "ppType"=>"batting", "runsScored"=>22}}, "wicketsData"=>{"wkt_1"=>{"batId"=>11172, "batName"=>"Finn Allen", "wktNbr"=>1, "wktOver"=>0.3, "wktRuns"=>0, "ballNbr"=>3}, "wkt_2"=>{"batId"=>9330, "batName"=>"Jennings", "wktNbr"=>2, "wktOver"=>4.5, "wktRuns"=>15, "ballNbr"=>45}, "wkt_3"=>{"batId"=>10637, "batName"=>"Josh Inglis", "wktNbr"=>3, "wktOver"=>6.4, "wktRuns"=>27, "ballNbr"=>64}, "wkt_4"=>{"batId"=>8506, "batName"=>"Turner", "wktNbr"=>4, "wktOver"=>8.1, "wktRuns"=>35, "ballNbr"=>81}, "wkt_5"=>{"batId"=>15758, "batName"=>"Matthew Spoors", "wktNbr"=>5, "wktOver"=>15.1, "wktRuns"=>84, "ballNbr"=>151}, "wkt_6"=>{"batId"=>11049, "batName"=>"Nick Hobson", "wktNbr"=>6, "wktOver"=>18.1, "wktRuns"=>126, "ballNbr"=>181}, "wkt_7"=>{"batId"=>8508, "batName"=>"Agar", "wktNbr"=>7, "wktOver"=>18.6, "wktRuns"=>130, "ballNbr"=>186}, "wkt_8"=>{"batId"=>15927, "batName"=>"Cooper Connolly", "wktNbr"=>8, "wktOver"=>19.2, "wktRuns"=>136, "ballNbr"=>192}}, "partnershipsData"=>{"pat_1"=>{"bat1Id"=>11172, "bat1Name"=>"Finn Allen", "bat1Runs"=>0, "bat1fours"=>0, "bat1sixes"=>0, "bat2Id"=>9330, "bat2Name"=>"Jennings", "bat2Runs"=>0, "bat2fours"=>0, "bat2sixes"=>0, "totalRuns"=>0, "totalBalls"=>3, "bat1balls"=>0, "bat2balls"=>0, "bat1Ones"=>0, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>0, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}, "pat_2"=>{"bat1Id"=>15927, "bat1Name"=>"Connolly", "bat1Runs"=>2, "bat1fours"=>0, "bat1sixes"=>0, "bat2Id"=>9330, "bat2Name"=>"Jennings", "bat2Runs"=>9, "bat2fours"=>1, "bat2sixes"=>0, "totalRuns"=>15, "totalBalls"=>26, "bat1balls"=>0, "bat2balls"=>0, "bat1Ones"=>0, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>0, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}, "pat_3"=>{"bat1Id"=>15927, "bat1Name"=>"Connolly", "bat1Runs"=>8, "bat1fours"=>0, "bat1sixes"=>1, "bat2Id"=>10637, "bat2Name"=>"Josh Inglis", "bat2Runs"=>4, "bat2fours"=>0, "bat2sixes"=>0, "totalRuns"=>12, "totalBalls"=>11, "bat1balls"=>0, "bat2balls"=>0, "bat1Ones"=>0, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>0, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}, "pat_4"=>{"bat1Id"=>15927, "bat1Name"=>"Connolly", "bat1Runs"=>0, "bat1fours"=>0, "bat1sixes"=>0, "bat2Id"=>8506, "bat2Name"=>"Turner", "bat2Runs"=>8, "bat2fours"=>1, "bat2sixes"=>0, "totalRuns"=>8, "totalBalls"=>9, "bat1balls"=>0, "bat2balls"=>0, "bat1Ones"=>0, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>0, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}, "pat_5"=>{"bat1Id"=>15927, "bat1Name"=>"Connolly", "bat1Runs"=>19, "bat1fours"=>0, "bat1sixes"=>1, "bat2Id"=>15758, "bat2Name"=>"Matthew Spoors", "bat2Runs"=>29, "bat2fours"=>1, "bat2sixes"=>2, "totalRuns"=>49, "totalBalls"=>42, "bat1balls"=>0, "bat2balls"=>0, "bat1Ones"=>0, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>0, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}, "pat_6"=>{"bat1Id"=>15927, "bat1Name"=>"Connolly", "bat1Runs"=>30, "bat1fours"=>1, "bat1sixes"=>3, "bat2Id"=>11049, "bat2Name"=>"Nick Hobson", "bat2Runs"=>8, "bat2fours"=>1, "bat2sixes"=>0, "totalRuns"=>42, "totalBalls"=>18, "bat1balls"=>0, "bat2balls"=>0, "bat1Ones"=>0, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>0, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}, "pat_7"=>{"bat1Id"=>15927, "bat1Name"=>"Connolly", "bat1Runs"=>1, "bat1fours"=>0, "bat1sixes"=>0, "bat2Id"=>8508, "bat2Name"=>"Agar", "bat2Runs"=>3, "bat2fours"=>0, "bat2sixes"=>0, "totalRuns"=>4, "totalBalls"=>5, "bat1balls"=>0, "bat2balls"=>0, "bat1Ones"=>0, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>0, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}, "pat_8"=>{"bat1Id"=>15927, "bat1Name"=>"Connolly", "bat1Runs"=>6, "bat1fours"=>0, "bat1sixes"=>1, "bat2Id"=>9451, "bat2Name"=>"Kelly", "bat2Runs"=>0, "bat2fours"=>0, "bat2sixes"=>0, "totalRuns"=>6, "totalBalls"=>2, "bat1balls"=>0, "bat2balls"=>0, "bat1Ones"=>0, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>0, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}, "pat_9"=>{"bat1Id"=>9617, "bat1Name"=>"Tye", "bat1Runs"=>4, "bat1fours"=>0, "bat1sixes"=>0, "bat2Id"=>9451, "bat2Name"=>"Kelly", "bat2Runs"=>2, "bat2fours"=>0, "bat2sixes"=>0, "totalRuns"=>7, "totalBalls"=>4, "bat1balls"=>0, "bat2balls"=>0, "bat1Ones"=>0, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>0, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}}}, {"matchId"=>101617, "inningsId"=>2, "timeScore"=>1734953597000, "batTeamDetails"=>{"batTeamId"=>195, "batTeamName"=>"Melbourne Renegades", "batTeamShortName"=>"MLR", "batsmenData"=>{"bat_1"=>{"batId"=>36307, "batName"=>"Josh Brown", "batShortName"=>"Josh Brown", "isCaptain"=>false, "isKeeper"=>false, "runs"=>12, "balls"=>6, "dots"=>2, "fours"=>2, "sixes"=>0, "mins"=>19, "strikeRate"=>200.0, "outDesc"=>"c Turner b Andrew Tye", "bowlerId"=>9617, "fielderId1"=>8506, "fielderId2"=>0, "fielderId3"=>0, "ones"=>1, "twos"=>0, "threes"=>1, "fives"=>0, "boundaries"=>2, "sixers"=>0, "wicketCode"=>"CAUGHT", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_2"=>{"batId"=>14501, "batName"=>"Jake Fraser-McGurk", "batShortName"=>"Jake Fraser-McGurk", "isCaptain"=>false, "isKeeper"=>false, "runs"=>2, "balls"=>4, "dots"=>3, "fours"=>0, "sixes"=>0, "mins"=>3, "strikeRate"=>50.0, "outDesc"=>"c Andrew Tye b Behrendorff", "bowlerId"=>7773, "fielderId1"=>9617, "fielderId2"=>0, "fielderId3"=>0, "ones"=>0, "twos"=>1, "threes"=>0, "fives"=>0, "boundaries"=>0, "sixers"=>0, "wicketCode"=>"CAUGHT", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_3"=>{"batId"=>9443, "batName"=>"Tim Seifert", "batShortName"=>"Seifert", "isCaptain"=>false, "isKeeper"=>true, "runs"=>28, "balls"=>14, "dots"=>6, "fours"=>5, "sixes"=>1, "mins"=>11, "strikeRate"=>200.0, "outDesc"=>"c Josh Inglis b Matthew Kelly", "bowlerId"=>9451, "fielderId1"=>10637, "fielderId2"=>0, "fielderId3"=>0, "ones"=>2, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>5, "sixers"=>1, "wicketCode"=>"CAUGHT", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_4"=>{"batId"=>19636, "batName"=>"Jacob Bethell", "batShortName"=>"Jacob Bethell", "isCaptain"=>false, "isKeeper"=>false, "runs"=>30, "balls"=>22, "dots"=>9, "fours"=>2, "sixes"=>2, "mins"=>25, "strikeRate"=>136.36, "outDesc"=>"b Agar", "bowlerId"=>8508, "fielderId1"=>0, "fielderId2"=>0, "fielderId3"=>0, "ones"=>8, "twos"=>1, "threes"=>0, "fives"=>0, "boundaries"=>2, "sixers"=>2, "wicketCode"=>"BOWLED", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_5"=>{"batId"=>6531, "batName"=>"Laurie Evans", "batShortName"=>"Laurie Evans", "isCaptain"=>false, "isKeeper"=>false, "runs"=>24, "balls"=>18, "dots"=>4, "fours"=>0, "sixes"=>1, "mins"=>26, "strikeRate"=>133.33, "outDesc"=>"c Behrendorff b Cooper Connolly", "bowlerId"=>15927, "fielderId1"=>7773, "fielderId2"=>0, "fielderId3"=>0, "ones"=>10, "twos"=>2, "threes"=>0, "fives"=>0, "boundaries"=>0, "sixers"=>1, "wicketCode"=>"CAUGHT", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_6"=>{"batId"=>13472, "batName"=>"Mackenzie Harvey", "batShortName"=>"Mackenzie Harvey", "isCaptain"=>false, "isKeeper"=>false, "runs"=>9, "balls"=>10, "dots"=>4, "fours"=>1, "sixes"=>0, "mins"=>12, "strikeRate"=>90.0, "outDesc"=>"b Turner", "bowlerId"=>8506, "fielderId1"=>0, "fielderId2"=>0, "fielderId3"=>0, "ones"=>5, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>1, "sixers"=>0, "wicketCode"=>"BOWLED", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_7"=>{"batId"=>12229, "batName"=>"Will Sutherland", "batShortName"=>"Sutherland", "isCaptain"=>true, "isKeeper"=>false, "runs"=>15, "balls"=>20, "dots"=>7, "fours"=>0, "sixes"=>0, "mins"=>33, "strikeRate"=>75.0, "outDesc"=>"not out", "bowlerId"=>0, "fielderId1"=>0, "fielderId2"=>0, "fielderId3"=>0, "ones"=>12, "twos"=>0, "threes"=>1, "fives"=>0, "boundaries"=>0, "sixers"=>0, "wicketCode"=>"", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_8"=>{"batId"=>13126, "batName"=>"Thomas Stewart Rogers", "batShortName"=>"Tom Rogers", "isCaptain"=>false, "isKeeper"=>false, "runs"=>5, "balls"=>7, "dots"=>2, "fours"=>0, "sixes"=>0, "mins"=>9, "strikeRate"=>71.43, "outDesc"=>"run out (Matthew Kelly)", "bowlerId"=>0, "fielderId1"=>9451, "fielderId2"=>0, "fielderId3"=>0, "ones"=>5, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>0, "sixers"=>0, "wicketCode"=>"RUNOUT", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_9"=>{"batId"=>24541, "batName"=>"Fergus O Neill", "batShortName"=>"Fergus O Neill", "isCaptain"=>false, "isKeeper"=>false, "runs"=>9, "balls"=>12, "dots"=>6, "fours"=>1, "sixes"=>0, "mins"=>11, "strikeRate"=>75.0, "outDesc"=>"c Turner b Behrendorff", "bowlerId"=>7773, "fielderId1"=>8506, "fielderId2"=>0, "fielderId3"=>0, "ones"=>5, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>1, "sixers"=>0, "wicketCode"=>"CAUGHT", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_10"=>{"batId"=>8642, "batName"=>"Adam Zampa", "batShortName"=>"Zampa", "isCaptain"=>false, "isKeeper"=>false, "runs"=>1, "balls"=>2, "dots"=>1, "fours"=>0, "sixes"=>0, "mins"=>2, "strikeRate"=>50.0, "outDesc"=>"not out", "bowlerId"=>0, "fielderId1"=>0, "fielderId2"=>0, "fielderId3"=>0, "ones"=>1, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>0, "sixers"=>0, "wicketCode"=>"", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bat_11"=>{"batId"=>6262, "batName"=>"Kane Richardson", "batShortName"=>"Kane Richardson", "isCaptain"=>false, "isKeeper"=>false, "runs"=>0, "balls"=>0, "dots"=>0, "fours"=>0, "sixes"=>0, "mins"=>0, "strikeRate"=>0.0, "outDesc"=>"", "bowlerId"=>0, "fielderId1"=>0, "fielderId2"=>0, "fielderId3"=>0, "ones"=>0, "twos"=>0, "threes"=>0, "fives"=>0, "boundaries"=>0, "sixers"=>0, "wicketCode"=>"", "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}}}, "bowlTeamDetails"=>{"bowlTeamId"=>197, "bowlTeamName"=>"Perth Scorchers", "bowlTeamShortName"=>"PRS", "bowlersData"=>{"bowl_1"=>{"bowlerId"=>7773, "bowlName"=>"Jason Behrendorff", "bowlShortName"=>"Behrendorff", "isCaptain"=>false, "isKeeper"=>false, "overs"=>4.0, "maidens"=>0, "runs"=>33, "wickets"=>2, "economy"=>8.2, "no_balls"=>0, "wides"=>0, "dots"=>0, "balls"=>0, "runsPerBall"=>0.0, "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bowl_2"=>{"bowlerId"=>9451, "bowlName"=>"Matthew Kelly", "bowlShortName"=>"Matthew Kelly", "isCaptain"=>false, "isKeeper"=>false, "overs"=>3.0, "maidens"=>0, "runs"=>33, "wickets"=>1, "economy"=>11.0, "no_balls"=>0, "wides"=>1, "dots"=>0, "balls"=>0, "runsPerBall"=>0.0, "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>"IN"}, "bowl_3"=>{"bowlerId"=>9617, "bowlName"=>"Andrew Tye", "bowlShortName"=>"Andrew Tye", "isCaptain"=>false, "isKeeper"=>false, "overs"=>3.0, "maidens"=>0, "runs"=>22, "wickets"=>1, "economy"=>7.3, "no_balls"=>1, "wides"=>0, "dots"=>0, "balls"=>0, "runsPerBall"=>0.0, "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>"IN"}, "bowl_4"=>{"bowlerId"=>15758, "bowlName"=>"Matthew Spoors", "bowlShortName"=>"Matthew Spoors", "isCaptain"=>false, "isKeeper"=>false, "overs"=>1.0, "maidens"=>0, "runs"=>15, "wickets"=>0, "economy"=>15.0, "no_balls"=>0, "wides"=>0, "dots"=>0, "balls"=>0, "runsPerBall"=>0.0, "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>"IN"}, "bowl_5"=>{"bowlerId"=>8508, "bowlName"=>"Ashton Agar", "bowlShortName"=>"Agar", "isCaptain"=>false, "isKeeper"=>false, "overs"=>4.0, "maidens"=>0, "runs"=>20, "wickets"=>1, "economy"=>5.0, "no_balls"=>0, "wides"=>3, "dots"=>0, "balls"=>0, "runsPerBall"=>0.0, "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bowl_6"=>{"bowlerId"=>15927, "bowlName"=>"Cooper Connolly", "bowlShortName"=>"Cooper Connolly", "isCaptain"=>false, "isKeeper"=>false, "overs"=>3.0, "maidens"=>0, "runs"=>17, "wickets"=>1, "economy"=>5.7, "no_balls"=>0, "wides"=>3, "dots"=>0, "balls"=>0, "runsPerBall"=>0.0, "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}, "bowl_7"=>{"bowlerId"=>8506, "bowlName"=>"Ashton Turner", "bowlShortName"=>"Turner", "isCaptain"=>true, "isKeeper"=>false, "overs"=>1.0, "maidens"=>0, "runs"=>3, "wickets"=>1, "economy"=>3.0, "no_balls"=>0, "wides"=>0, "dots"=>0, "balls"=>0, "runsPerBall"=>0.0, "isOverseas"=>false, "inMatchChange"=>"", "playingXIChange"=>""}}}, "scoreDetails"=>{"ballNbr"=>114, "isDeclared"=>false, "isFollowOn"=>false, "overs"=>19.0, "revisedOvers"=>0.0, "runRate"=>7.58, "runs"=>144, "wickets"=>8, "runsPerBall"=>0.76}, "extrasData"=>{"noBalls"=>1, "total"=>9, "byes"=>0, "penalty"=>0, "wides"=>7, "legByes"=>1}, "ppData"=>{"pp_1"=>{"ppId"=>5, "ppOversFrom"=>0.1, "ppOversTo"=>4.0, "ppType"=>"mandatory", "runsScored"=>42}, "pp_2"=>{"ppId"=>6, "ppOversFrom"=>18.1, "ppOversTo"=>20.0, "ppType"=>"batting", "runsScored"=>6}}, "wicketsData"=>{"wkt_1"=>{"batId"=>14501, "batName"=>"Jake Fraser-McGurk", "wktNbr"=>1, "wktOver"=>0.6, "wktRuns"=>9, "ballNbr"=>6}, "wkt_2"=>{"batId"=>9443, "batName"=>"Tim Seifert", "wktNbr"=>2, "wktOver"=>3.4, "wktRuns"=>42, "ballNbr"=>34}, "wkt_3"=>{"batId"=>36307, "batName"=>"Josh Brown", "wktNbr"=>3, "wktOver"=>4.2, "wktRuns"=>42, "ballNbr"=>42}, "wkt_4"=>{"batId"=>19636, "batName"=>"Jacob Bethell", "wktNbr"=>4, "wktOver"=>9.4, "wktRuns"=>96, "ballNbr"=>94}, "wkt_5"=>{"batId"=>6531, "batName"=>"Laurie Evans", "wktNbr"=>5, "wktOver"=>10.6, "wktRuns"=>103, "ballNbr"=>106}, "wkt_6"=>{"batId"=>13472, "batName"=>"Mackenzie Harvey", "wktNbr"=>6, "wktOver"=>13.3, "wktRuns"=>113, "ballNbr"=>133}, "wkt_7"=>{"batId"=>13126, "batName"=>"Thomas Stewart Rogers", "wktNbr"=>7, "wktOver"=>16.0, "wktRuns"=>128, "ballNbr"=>160}, "wkt_8"=>{"batId"=>24541, "batName"=>"Fergus O Neill", "wktNbr"=>8, "wktOver"=>18.3, "wktRuns"=>140, "ballNbr"=>183}}, "partnershipsData"=>{"pat_1"=>{"bat1Id"=>36307, "bat1Name"=>"Josh Brown", "bat1Runs"=>7, "bat1fours"=>1, "bat1sixes"=>0, "bat2Id"=>14501, "bat2Name"=>"Fraser-McGurk", "bat2Runs"=>2, "bat2fours"=>0, "bat2sixes"=>0, "totalRuns"=>9, "totalBalls"=>6, "bat1balls"=>2, "bat2balls"=>4, "bat1Ones"=>0, "bat1Twos"=>0, "bat1Threes"=>1, "bat1Fives"=>0, "bat1Boundaries"=>1, "bat1Sixers"=>0, "bat2Ones"=>0, "bat2Twos"=>1, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}, "pat_2"=>{"bat1Id"=>36307, "bat1Name"=>"Josh Brown", "bat1Runs"=>5, "bat1fours"=>1, "bat1sixes"=>0, "bat2Id"=>9443, "bat2Name"=>"Seifert", "bat2Runs"=>28, "bat2fours"=>5, "bat2sixes"=>1, "totalRuns"=>33, "totalBalls"=>16, "bat1balls"=>2, "bat2balls"=>14, "bat1Ones"=>1, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>1, "bat1Sixers"=>0, "bat2Ones"=>2, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>5, "bat2Sixers"=>1}, "pat_3"=>{"bat1Id"=>36307, "bat1Name"=>"Josh Brown", "bat1Runs"=>0, "bat1fours"=>0, "bat1sixes"=>0, "bat2Id"=>19636, "bat2Name"=>"Jacob Bethell", "bat2Runs"=>0, "bat2fours"=>0, "bat2sixes"=>0, "totalRuns"=>0, "totalBalls"=>4, "bat1balls"=>2, "bat2balls"=>2, "bat1Ones"=>0, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>0, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}, "pat_4"=>{"bat1Id"=>6531, "bat1Name"=>"Laurie Evans", "bat1Runs"=>22, "bat1fours"=>1, "bat1sixes"=>1, "bat2Id"=>19636, "bat2Name"=>"Jacob Bethell", "bat2Runs"=>30, "bat2fours"=>2, "bat2sixes"=>2, "totalRuns"=>54, "totalBalls"=>33, "bat1balls"=>13, "bat2balls"=>20, "bat1Ones"=>8, "bat1Twos"=>2, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>1, "bat2Ones"=>8, "bat2Twos"=>1, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>2, "bat2Sixers"=>2}, "pat_5"=>{"bat1Id"=>6531, "bat1Name"=>"Laurie Evans", "bat1Runs"=>2, "bat1fours"=>0, "bat1sixes"=>0, "bat2Id"=>13472, "bat2Name"=>"Mackenzie Harvey", "bat2Runs"=>2, "bat2fours"=>0, "bat2sixes"=>0, "totalRuns"=>7, "totalBalls"=>8, "bat1balls"=>5, "bat2balls"=>3, "bat1Ones"=>2, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>2, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}, "pat_6"=>{"bat1Id"=>12229, "bat1Name"=>"Sutherland", "bat1Runs"=>3, "bat1fours"=>0, "bat1sixes"=>0, "bat2Id"=>13472, "bat2Name"=>"Mackenzie Harvey", "bat2Runs"=>7, "bat2fours"=>1, "bat2sixes"=>0, "totalRuns"=>10, "totalBalls"=>15, "bat1balls"=>8, "bat2balls"=>7, "bat1Ones"=>3, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>3, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>1, "bat2Sixers"=>0}, "pat_7"=>{"bat1Id"=>12229, "bat1Name"=>"Sutherland", "bat1Runs"=>7, "bat1fours"=>0, "bat1sixes"=>0, "bat2Id"=>13126, "bat2Name"=>"Tom Rogers", "bat2Runs"=>5, "bat2fours"=>0, "bat2sixes"=>0, "totalRuns"=>16, "totalBalls"=>15, "bat1balls"=>8, "bat2balls"=>7, "bat1Ones"=>5, "bat1Twos"=>1, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>5, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}, "pat_8"=>{"bat1Id"=>12229, "bat1Name"=>"Sutherland", "bat1Runs"=>3, "bat1fours"=>0, "bat1sixes"=>0, "bat2Id"=>24541, "bat2Name"=>"Fergus O Neill", "bat2Runs"=>9, "bat2fours"=>1, "bat2sixes"=>0, "totalRuns"=>12, "totalBalls"=>15, "bat1balls"=>3, "bat2balls"=>12, "bat1Ones"=>3, "bat1Twos"=>0, "bat1Threes"=>0, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>5, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>1, "bat2Sixers"=>0}, "pat_9"=>{"bat1Id"=>12229, "bat1Name"=>"Sutherland", "bat1Runs"=>3, "bat1fours"=>0, "bat1sixes"=>0, "bat2Id"=>8642, "bat2Name"=>"Zampa", "bat2Runs"=>1, "bat2fours"=>0, "bat2sixes"=>0, "totalRuns"=>4, "totalBalls"=>3, "bat1balls"=>1, "bat2balls"=>2, "bat1Ones"=>0, "bat1Twos"=>0, "bat1Threes"=>1, "bat1Fives"=>0, "bat1Boundaries"=>0, "bat1Sixers"=>0, "bat2Ones"=>1, "bat2Twos"=>0, "bat2Threes"=>0, "bat2Fives"=>0, "bat2Boundaries"=>0, "bat2Sixers"=>0}}}], "matchHeader"=>{"matchId"=>101617, "matchDescription"=>"10th Match", "matchFormat"=>"T20", "matchType"=>"league", "complete"=>true, "domestic"=>false, "matchStartTimestamp"=>1734941700000, "matchCompleteTimestamp"=>1734953628603, "dayNight"=>false, "year"=>2024, "state"=>"Complete", "status"=>"Melbourne Renegades won by 2 wkts", "tossResults"=>{"tossWinnerId"=>195, "tossWinnerName"=>"Melbourne Renegades", "decision"=>"Bowling"}, "result"=>{"resultType"=>"win", "winningTeam"=>"Melbourne Renegades", "winningteamId"=>195, "winningMargin"=>2, "winByRuns"=>false, "winByInnings"=>false}, "revisedTarget"=>{"reason"=>""}, "playersOfTheMatch"=>[{"id"=>13126, "name"=>"Tom Rogers", "fullName"=>"Thomas Stewart Rogers", "nickName"=>"Tom Rogers", "captain"=>false, "keeper"=>false, "substitute"=>false, "teamName"=>"Tasmania", "faceImageId"=>151564}], "playersOfTheSeries"=>[], "matchTeamInfo"=>[{"battingTeamId"=>197, "battingTeamShortName"=>"PRS", "bowlingTeamId"=>195, "bowlingTeamShortName"=>"MLR"}, {"battingTeamId"=>195, "battingTeamShortName"=>"MLR", "bowlingTeamId"=>197, "bowlingTeamShortName"=>"PRS"}], "isMatchNotCovered"=>false, "team1"=>{"id"=>195, "name"=>"Melbourne Renegades", "playerDetails"=>[], "shortName"=>"MLR"}, "team2"=>{"id"=>197, "name"=>"Perth Scorchers", "playerDetails"=>[], "shortName"=>"PRS"}, "seriesDesc"=>"Big Bash League 2024-25", "seriesId"=>8535, "seriesName"=>"Big Bash League 2024-25", "alertType"=>"auto", "livestreamEnabled"=>false}, "isMatchComplete"=>true, "status"=>"Melbourne Renegades won by 2 wkts", "videos"=>[], "responseLastUpdated"=>1735737611
    }.freeze
    SERIES = { 'matchType' => 'League',
               'seriesMatches' =>
      [{ 'seriesAdWrapper' =>
         { 'seriesId' => 8535,
           'seriesName' => 'Big Bash League 2024-25',
           'matches' =>
           [{ 'matchInfo' =>
              { 'matchId' => 101_640,
                'seriesId' => 8535,
                'seriesName' => 'Big Bash League 2024-25',
                'matchDesc' => '13th Match',
                'matchFormat' => 'T20',
                'startDate' => '1735287300000',
                'endDate' => '1735299900000',
                'state' => 'Complete',
                'status' => 'Hobart Hurricanes won by 11 runs',
                'team1' => { 'teamId' => 194, 'teamName' => 'Hobart Hurricanes', 'teamSName' => 'HBH',
                             'imageId' => 172_254 },
                'team2' => { 'teamId' => 199, 'teamName' => 'Adelaide Strikers', 'teamSName' => 'ADS',
                             'imageId' => 172_259 },
                'venueInfo' =>
                { 'id' => 40, 'ground' => 'Adelaide Oval', 'city' => 'Adelaide', 'timezone' => '+10:30', 'latitude' => '-34.915516',
                  'longitude' => '138.596115' },
                'currBatTeamId' => 194,
                'seriesStartDt' => '1734220800000',
                'seriesEndDt' => '1738108800000',
                'isTimeAnnounced' => true,
                'stateTitle' => 'HBH Won',
                'isFantasyEnabled' => true },
              'matchScore' =>
              { 'team1Score' => { 'inngs1' => { 'inningsId' => 1, 'runs' => 214, 'wickets' => 5, 'overs' => 19.6 } },
                'team2Score' => { 'inngs1' => { 'inningsId' => 2, 'runs' => 203, 'wickets' => 6,
                                                'overs' => 19.6 } } } },
            { 'matchInfo' =>
              { 'matchId' => 101_635,
                'seriesId' => 8535,
                'seriesName' => 'Big Bash League 2024-25',
                'matchDesc' => '12th Match',
                'matchFormat' => 'T20',
                'startDate' => '1735208100000',
                'endDate' => '1735220700000',
                'state' => 'Complete',
                'status' => 'Perth Scorchers won by 33 runs',
                'team1' => { 'teamId' => 197, 'teamName' => 'Perth Scorchers', 'teamSName' => 'PRS',
                             'imageId' => 172_257 },
                'team2' => { 'teamId' => 193, 'teamName' => 'Brisbane Heat', 'teamSName' => 'BRH',
                             'imageId' => 172_253 },
                'venueInfo' =>
                { 'id' => 512, 'ground' => 'Perth Stadium', 'city' => 'Perth', 'timezone' => '+08:00', 'latitude' => '-31.9496122',
                  'longitude' => '115.7858493' },
                'currBatTeamId' => 197,
                'seriesStartDt' => '1734220800000',
                'seriesEndDt' => '1738108800000',
                'isTimeAnnounced' => true,
                'stateTitle' => 'PRS Won',
                'isFantasyEnabled' => true },
              'matchScore' =>
              { 'team1Score' => { 'inngs1' => { 'inningsId' => 1, 'runs' => 165, 'wickets' => 6, 'overs' => 19.6 } },
                'team2Score' => { 'inngs1' => { 'inningsId' => 2, 'runs' => 132, 'wickets' => 10,
                                                'overs' => 19.4 } } } },
            { 'matchInfo' =>
              { 'matchId' => 101_626,
                'seriesId' => 8535,
                'seriesName' => 'Big Bash League 2024-25',
                'matchDesc' => '11th Match',
                'matchFormat' => 'T20',
                'startDate' => '1735196700000',
                'endDate' => '1735209300000',
                'state' => 'Complete',
                'status' => 'Sydney Sixers won by 8 wkts',
                'team1' => { 'teamId' => 196, 'teamName' => 'Melbourne Stars', 'teamSName' => 'MLS',
                             'imageId' => 172_256 },
                'team2' => { 'teamId' => 198, 'teamName' => 'Sydney Sixers', 'teamSName' => 'SYS',
                             'imageId' => 172_258 },
                'venueInfo' =>
                { 'id' => 34,
                  'ground' => 'Sydney Cricket Ground',
                  'city' => 'Sydney',
                  'timezone' => '+11:00',
                  'latitude' => '-33.868820',
                  'longitude' => '151.209296' },
                'currBatTeamId' => 198,
                'seriesStartDt' => '1734220800000',
                'seriesEndDt' => '1738108800000',
                'isTimeAnnounced' => true,
                'stateTitle' => 'SYS Won',
                'isFantasyEnabled' => true },
              'matchScore' =>
              { 'team1Score' => { 'inngs1' => { 'inningsId' => 1, 'runs' => 194, 'wickets' => 9, 'overs' => 19.6 } },
                'team2Score' => { 'inngs1' => { 'inningsId' => 2, 'runs' => 198, 'wickets' => 2,
                                                'overs' => 18.1 } } } },
            { 'matchInfo' =>
              { 'matchId' => 101_617,
                'seriesId' => 8535,
                'seriesName' => 'Big Bash League 2024-25',
                'matchDesc' => '10th Match',
                'matchFormat' => 'T20',
                'startDate' => '1734941700000',
                'endDate' => '1734954300000',
                'state' => 'Complete',
                'status' => 'Melbourne Renegades won by 2 wkts',
                'team1' => { 'teamId' => 197, 'teamName' => 'Perth Scorchers', 'teamSName' => 'PRS',
                             'imageId' => 172_257 },
                'team2' => { 'teamId' => 195, 'teamName' => 'Melbourne Renegades', 'teamSName' => 'MLR',
                             'imageId' => 172_255 },
                'venueInfo' =>
                { 'id' => 33,
                  'ground' => 'Docklands Stadium',
                  'city' => 'Melbourne',
                  'timezone' => '+11:00',
                  'latitude' => '28.083627',
                  'longitude' => '-80.608109' },
                'currBatTeamId' => 195,
                'seriesStartDt' => '1734220800000',
                'seriesEndDt' => '1738108800000',
                'isTimeAnnounced' => true,
                'stateTitle' => 'MLR Won',
                'isFantasyEnabled' => true },
              'matchScore' =>
              { 'team1Score' => { 'inngs1' => { 'inningsId' => 1, 'runs' => 143, 'wickets' => 8, 'overs' => 19.6 } },
                'team2Score' => { 'inngs1' => { 'inningsId' => 2, 'runs' => 144, 'wickets' => 8,
                                                'overs' => 18.6 } } } },
            { 'matchInfo' =>
              { 'matchId' => 101_613,
                'seriesId' => 8535,
                'seriesName' => 'Big Bash League 2024-25',
                'matchDesc' => '9th Match',
                'matchFormat' => 'T20',
                'startDate' => '1734855300000',
                'endDate' => '1734867900000',
                'state' => 'Complete',
                'status' => 'Brisbane Heat won by 3 wkts',
                'team1' => { 'teamId' => 199, 'teamName' => 'Adelaide Strikers', 'teamSName' => 'ADS',
                             'imageId' => 172_259 },
                'team2' => { 'teamId' => 193, 'teamName' => 'Brisbane Heat', 'teamSName' => 'BRH',
                             'imageId' => 172_253 },
                'venueInfo' =>
                { 'id' => 35, 'ground' => 'The Gabba', 'city' => 'Brisbane', 'timezone' => '+10:00', 'latitude' => '-27.485829',
                  'longitude' => '153.038055' },
                'currBatTeamId' => 193,
                'seriesStartDt' => '1734220800000',
                'seriesEndDt' => '1738108800000',
                'isTimeAnnounced' => true,
                'stateTitle' => 'BRH Won',
                'isFantasyEnabled' => true },
              'matchScore' =>
              { 'team1Score' => { 'inngs1' => { 'inningsId' => 1, 'runs' => 174, 'wickets' => 6, 'overs' => 19.6 } },
                'team2Score' => { 'inngs1' => { 'inningsId' => 2, 'runs' => 175, 'wickets' => 7,
                                                'overs' => 19.6 } } } },
            { 'matchInfo' =>
              { 'matchId' => 101_608,
                'seriesId' => 8535,
                'seriesName' => 'Big Bash League 2024-25',
                'matchDesc' => '8th Match',
                'matchFormat' => 'T20',
                'startDate' => '1734768900000',
                'endDate' => '1734781500000',
                'state' => 'Complete',
                'status' => 'Sydney Sixers won by 5 wkts',
                'team1' => { 'teamId' => 192, 'teamName' => 'Sydney Thunder', 'teamSName' => 'SYT',
                             'imageId' => 172_252 },
                'team2' => { 'teamId' => 198, 'teamName' => 'Sydney Sixers', 'teamSName' => 'SYS',
                             'imageId' => 172_258 },
                'venueInfo' =>
                { 'id' => 396,
                  'ground' => 'Sydney Showground Stadium',
                  'city' => 'Sydney',
                  'timezone' => '+11:00',
                  'latitude' => '-33.843277',
                  'longitude' => '151.067879' },
                'currBatTeamId' => 198,
                'seriesStartDt' => '1734220800000',
                'seriesEndDt' => '1738108800000',
                'isTimeAnnounced' => true,
                'stateTitle' => 'SYS Won',
                'isFantasyEnabled' => true },
              'matchScore' =>
              { 'team1Score' => { 'inngs1' => { 'inningsId' => 1, 'runs' => 163, 'wickets' => 5, 'overs' => 19.6 } },
                'team2Score' => { 'inngs1' => { 'inningsId' => 2, 'runs' => 164, 'wickets' => 5,
                                                'overs' => 19.6 } } } }] } },
       { 'seriesAdWrapper' =>
         { 'seriesId' => 8979,
           'seriesName' => 'Super Smash 2024-25',
           'matches' =>
           [{ 'matchInfo' =>
              { 'matchId' => 107_841,
                'seriesId' => 8979,
                'seriesName' => 'Super Smash 2024-25',
                'matchDesc' => '2nd Match',
                'matchFormat' => 'T20',
                'startDate' => '1735269900000',
                'endDate' => '1735282500000',
                'state' => 'Complete',
                'status' => 'Otago won by 10 runs',
                'team1' => { 'teamId' => 105, 'teamName' => 'Otago', 'teamSName' => 'OTG', 'imageId' => 172_197 },
                'team2' => { 'teamId' => 312, 'teamName' => 'Canterbury', 'teamSName' => 'CNTBRY',
                             'imageId' => 172_362 },
                'venueInfo' =>
                { 'id' => 423,
                  'ground' => 'Molyneux Park',
                  'city' => 'Alexandra',
                  'timezone' => '+13:00',
                  'latitude' => '-45.242832362',
                  'longitude' => '169.3745' },
                'currBatTeamId' => 105,
                'seriesStartDt' => '1735171200000',
                'seriesEndDt' => '1738627200000',
                'isTimeAnnounced' => true,
                'stateTitle' => 'OTG Won' },
              'matchScore' =>
              { 'team1Score' => { 'inngs1' => { 'inningsId' => 1, 'runs' => 165, 'wickets' => 9, 'overs' => 19.6 } },
                'team2Score' => { 'inngs1' => { 'inningsId' => 2, 'runs' => 155, 'wickets' => 10,
                                                'overs' => 19.6 } } } },
            { 'matchInfo' =>
              { 'matchId' => 107_835,
                'seriesId' => 8979,
                'seriesName' => 'Super Smash 2024-25',
                'matchDesc' => '1st Match',
                'matchFormat' => 'T20',
                'startDate' => '1735188900000',
                'endDate' => '1735201500000',
                'state' => 'Complete',
                'status' => 'Match abandoned due to rain (no toss)',
                'team1' => { 'teamId' => 294, 'teamName' => 'Northern Knights', 'teamSName' => 'MR',
                             'imageId' => 172_343 },
                'team2' => { 'teamId' => 186, 'teamName' => 'Auckland', 'teamSName' => 'PS', 'imageId' => 172_246 },
                'venueInfo' =>
                { 'id' => 100, 'ground' => 'Seddon Park', 'city' => 'Hamilton', 'timezone' => '+13:00', 'latitude' => '-37.786654',
                  'longitude' => '175.266647' },
                'seriesStartDt' => '1735171200000',
                'seriesEndDt' => '1738627200000',
                'isTimeAnnounced' => true,
                'stateTitle' => 'Abandon' } }] } }] }.freeze
  end
end
